import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// ── 10 Real Indian Vendors ─────────────────────────────────────────────
const vendors = [
  {
    id: "v1",
    businessName: "TechZone Electronics",
    storeSlug: "techzone",
    tagline: "Premier Destination for Flagship Tech, Audio & Wearables with Express Dispatch",
    ownerName: "Rajesh Kumar",
    email: "rajesh@techzone.in",
    password: "Vendor@123",
    mobile: "9876543210",
    businessAddress: "14, Electronics Street, Nehru Place",
    location: "New Delhi, Delhi",
    joinedDate: "2024-01-15",
    avatar: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=120&h=120&fit=crop",
    banner: "https://images.unsplash.com/photo-1550009158-9ebf69173e03?w=1200&h=300&fit=crop",
    themeColor: "#4F46E5",
    themePreset: "indigo",
    storeStatus: "published",
    isVerified: true,
    gstin: "07AABCT1234F1Z8",
    announcement: "⚡ Same-Day Courier Dispatch across India & 1-Year Direct Brand Warranty!",
    featuredProductIds: ["p1", "p2", "p3", "p4"],
    storeRating: 4.8,
    totalOrdersFulfilled: 1240,
    onTimeDispatchRate: "98.8%",
    shippingPartners: ["BlueDart Express", "Delhivery Surface", "DTDC Air"],
    returnPolicy: "7 Days Hassle-Free Physical Replacement or Full Refund",
    warrantyPolicy: "100% Verified Brand Warranty & Tax Invoice Included",
    description: "Official verified physical retail store of TechZone Electronics. We stock 100% genuine consumer electronics with same-day warehouse dispatch."
  },
  {
    id: "v2",
    businessName: "StyleHub Fashion",
    storeSlug: "stylehub",
    tagline: "Curated Contemporary Apparel, Pure Silk Sarees & Handcrafted Footwear",
    ownerName: "Priya Sharma",
    email: "priya@stylehub.in",
    password: "Vendor@123",
    mobile: "9123456789",
    businessAddress: "5, Fashion Lane, Linking Road, Bandra West",
    location: "Mumbai, Maharashtra",
    joinedDate: "2024-02-20",
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=120&h=120&fit=crop",
    banner: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=1200&h=300&fit=crop",
    themeColor: "#EC4899",
    themePreset: "rose",
    storeStatus: "published",
    isVerified: true,
    gstin: "27AABCS5678G2Z1",
    announcement: "✨ Festive Collection Live: Complimentary Garment Care Kit on orders above ₹2,499!",
    featuredProductIds: ["p16", "p17", "p18", "p19"],
    storeRating: 4.8,
    totalOrdersFulfilled: 1555,
    onTimeDispatchRate: "99.1%",
    shippingPartners: ["BlueDart Express", "Delhivery Surface", "DTDC Air"],
    returnPolicy: "7 Days Hassle-Free Physical Replacement or Full Refund",
    warrantyPolicy: "100% Authentic Fabric & Quality Assurance Guarantee",
    description: "StyleHub Fashion brings handpicked designer wear, handcrafted Banarasi silks, and tailored wardrobe essentials from master artisans across India."
  },
  {
    id: "v3",
    businessName: "FreshBazaar Grocery",
    storeSlug: "freshbazaar",
    tagline: "Single-Estate Cold-Pressed Oils, Organic Staples & Rare Himalayan Superfoods",
    ownerName: "Amit Patel",
    email: "amit@freshbazaar.in",
    password: "Vendor@123",
    mobile: "9988776655",
    businessAddress: "22, Market Road, Majestic",
    location: "Bengaluru, Karnataka",
    joinedDate: "2024-03-10",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&h=120&fit=crop",
    banner: "https://images.unsplash.com/photo-1542838132-92c53300491e?w=1200&h=300&fit=crop",
    themeColor: "#059669",
    themePreset: "emerald",
    storeStatus: "published",
    isVerified: true,
    gstin: "29AABCF9012H3Z4",
    announcement: "🌿 100% Certified Organic Warehouse Stock with Nitrogen-Flushed Tamper-Proof Packaging.",
    featuredProductIds: ["p31", "p32", "p33", "p34"],
    storeRating: 4.9,
    totalOrdersFulfilled: 1870,
    onTimeDispatchRate: "99.4%",
    shippingPartners: ["BlueDart Express", "Delhivery Surface", "Shadowfax"],
    returnPolicy: "7 Days Replacement for sealed grocery items upon delivery inspection",
    warrantyPolicy: "FSSAI Certified, 100% Pesticide-Free Laboratory Tested",
    description: "FreshBazaar connects health-conscious households with organic farm cooperatives producing A2 cultured ghee, cold-pressed oils, and pure superfoods."
  },
  {
    id: "v4",
    businessName: "HomeEssentials Store",
    storeSlug: "homeessentials",
    tagline: "Pre-Seasoned Cast Iron Cookware, Tri-Ply Steel & Kitchen Ergonomics",
    ownerName: "Sunita Rao",
    email: "sunita@homeessentials.in",
    password: "Vendor@123",
    mobile: "9765432100",
    businessAddress: "7, Gandhi Nagar, Park Street",
    location: "Kolkata, West Bengal",
    joinedDate: "2024-04-05",
    avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=120&h=120&fit=crop",
    banner: "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=1200&h=300&fit=crop",
    themeColor: "#D97706",
    themePreset: "amber",
    storeStatus: "published",
    isVerified: true,
    gstin: "19AABCH3456J4Z7",
    announcement: "🏠 Free Silicone Hot Handle Grips included with every Cast Iron Cookware order!",
    featuredProductIds: ["p46", "p47", "p48", "p49"],
    storeRating: 4.8,
    totalOrdersFulfilled: 2185,
    onTimeDispatchRate: "98.7%",
    shippingPartners: ["BlueDart Express", "Delhivery Surface", "DTDC Air"],
    returnPolicy: "7 Days Hassle-Free Physical Replacement or Full Refund",
    warrantyPolicy: "5-Year Structural Replacement Warranty on Heavy Cast Iron",
    description: "HomeEssentials Store crafts heirloom-quality kitchenware designed to last generations, combining traditional metallurgy with modern ergonomic standards."
  },
  {
    id: "v5",
    businessName: "Apex Sports & Outdoors",
    storeSlug: "apexsports",
    tagline: "High-Performance Athletics, Tournament Badminton & Calisthenics Equipment",
    ownerName: "Vikram Malhotra",
    email: "vikram@apexsports.in",
    password: "Vendor@123",
    mobile: "9845123456",
    businessAddress: "88, Jubilee Hills Road No. 36",
    location: "Hyderabad, Telangana",
    joinedDate: "2024-07-10",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&h=120&fit=crop",
    banner: "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=1200&h=300&fit=crop",
    themeColor: "#EA580C",
    themePreset: "orange",
    storeStatus: "published",
    isVerified: true,
    gstin: "36AABCA7890K1Z2",
    announcement: "🔥 New Merchant Special: Priority Express Courier Dispatch across India within 18 hours!",
    featuredProductIds: ["p61", "p62", "p63", "p64"],
    storeRating: 4.9,
    totalOrdersFulfilled: 74,
    onTimeDispatchRate: "99.5%",
    shippingPartners: ["BlueDart Express", "Delhivery Surface", "DTDC Air"],
    returnPolicy: "7 Days Physical Replacement for Sports Equipment",
    warrantyPolicy: "1-Year Official Manufacturer Warranty on all Rackets & Gym Gear",
    description: "Apex Sports is an emerging boutique retailer in Hyderabad supplying tournament-grade badminton racquets, Olympic gym dumbbells, and mountain biking gear."
  },
  {
    id: "v6",
    businessName: "GlowAura Beauty & Wellness",
    storeSlug: "glowaura",
    tagline: "Clean Ayurvedic Formulations, Botanical Face Elixirs & Organic Hair Spa",
    ownerName: "Ananya Iyer",
    email: "ananya@glowaura.in",
    password: "Vendor@123",
    mobile: "9789012345",
    businessAddress: "42, Khader Nawaz Khan Road, Nungambakkam",
    location: "Chennai, Tamil Nadu",
    joinedDate: "2024-08-01",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=120&h=120&fit=crop",
    banner: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=1200&h=300&fit=crop",
    themeColor: "#8B5CF6",
    themePreset: "purple",
    storeStatus: "published",
    isVerified: true,
    gstin: "33AABCG1234L2Z3",
    announcement: "🌸 100% Cruelty-Free, Zero Parabens, Handcrafted in small fresh apothecary batches.",
    featuredProductIds: ["p76", "p77", "p78", "p79"],
    storeRating: 4.9,
    totalOrdersFulfilled: 58,
    onTimeDispatchRate: "99.2%",
    shippingPartners: ["BlueDart Express", "Delhivery Surface"],
    returnPolicy: "7 Days Return on unopened products with intact safety seals",
    warrantyPolicy: "Dermatologically Tested & Ayush Ministry Certified",
    description: "GlowAura Beauty is a Chennai-based clean apothecary formulating pure Kumkumadi facial oils, Kannauj rose water, and organic hair restoration solutions."
  },
  {
    id: "v7",
    businessName: "CraftArtisans Studio",
    storeSlug: "craftartisans",
    tagline: "GI-Tagged Jaipur Blue Pottery, Brass Statues & Handwoven Jute Kilims",
    ownerName: "Mohanlal Kumawat",
    email: "mohanlal@craftartisans.in",
    password: "Vendor@123",
    mobile: "9414012345",
    businessAddress: "19, Amber Fort Road, Sanganer",
    location: "Jaipur, Rajasthan",
    joinedDate: "2024-08-15",
    avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=120&h=120&fit=crop",
    banner: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=1200&h=300&fit=crop",
    themeColor: "#0284C7",
    themePreset: "sky",
    storeStatus: "published",
    isVerified: true,
    gstin: "08AABCC5678M3Z4",
    announcement: "🏺 Direct-from-Artisan: Custom double-layered bubble packaging ensures 0 transit breakage.",
    featuredProductIds: ["p91", "p92", "p93", "p94"],
    storeRating: 4.9,
    totalOrdersFulfilled: 42,
    onTimeDispatchRate: "98.9%",
    shippingPartners: ["BlueDart Express", "Delhivery Surface", "DTDC Air"],
    returnPolicy: "100% Free Replacement for any item damaged during physical transit",
    warrantyPolicy: "Authentic Handicraft Certificate & Origin Verification Included",
    description: "Direct heritage craft collective in Jaipur preserving 500-year-old Blue Pottery techniques, bell-metal casting, and block-printed home furnishings."
  },
  {
    id: "v8",
    businessName: "UrbanDen Home & Office",
    storeSlug: "urbanden",
    tagline: "Minimalist Solid Oak Monitor Stands, Desk Blotters & Ergonomic Tools",
    ownerName: "Rohan Kulkarni",
    email: "rohan@urbanden.in",
    password: "Vendor@123",
    mobile: "9822012345",
    businessAddress: "104, IT Park Road, Aundh",
    location: "Pune, Maharashtra",
    joinedDate: "2024-08-20",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&h=120&fit=crop",
    banner: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&h=300&fit=crop",
    themeColor: "#475569",
    themePreset: "slate",
    storeStatus: "published",
    isVerified: true,
    gstin: "27AABCU9012N4Z5",
    announcement: "🖥️ Transform your WFH desk setup: Complimentary cable management straps with every stand!",
    featuredProductIds: ["p106", "p107", "p108", "p109"],
    storeRating: 4.8,
    totalOrdersFulfilled: 36,
    onTimeDispatchRate: "99.0%",
    shippingPartners: ["BlueDart Express", "Delhivery Surface"],
    returnPolicy: "7 Days Hassle-Free Physical Replacement or Full Refund",
    warrantyPolicy: "3-Year Solid Hardwood Structural Guarantee",
    description: "UrbanDen designs productivity-boosting desktop accessories using sustainably sourced oak wood, heavy-gauge aluminum, and vegan leather."
  },
  {
    id: "v9",
    businessName: "GreenLeaf Plant Boutique",
    storeSlug: "greenleaf",
    tagline: "Nursery-Conditioned Exotic Houseplants, Terracotta Planters & Plant Care",
    ownerName: "Meera Nambiar",
    email: "meera@greenleaf.in",
    password: "Vendor@123",
    mobile: "9847012345",
    businessAddress: "12, Panampilly Nagar Main Avenue",
    location: "Kochi, Kerala",
    joinedDate: "2024-09-01",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&h=120&fit=crop",
    banner: "https://images.unsplash.com/photo-1463320726281-696a485928c7?w=1200&h=300&fit=crop",
    themeColor: "#16A34A",
    themePreset: "green",
    storeStatus: "published",
    isVerified: true,
    gstin: "32AABCG3456P5Z6",
    announcement: "🌱 Live Plant Guarantee: Guaranteed healthy arrival or instant free doorstep replacement.",
    featuredProductIds: ["p121", "p122", "p123", "p124"],
    storeRating: 4.9,
    totalOrdersFulfilled: 29,
    onTimeDispatchRate: "99.8%",
    shippingPartners: ["BlueDart Air Priority", "Delhivery Express"],
    returnPolicy: "Guaranteed Healthy Delivery: 48-Hour Live Plant Replacement Guarantee",
    warrantyPolicy: "Potted in organic nutrient-rich soil mix with care instructions",
    description: "GreenLeaf Boutique grows resilient, air-purifying indoor plants packaged with specialized breathable root-protective cartons for safe express delivery."
  },
  {
    id: "v10",
    businessName: "SoundMaster Pro Audio",
    storeSlug: "soundmaster",
    tagline: "Studio Microphones, Audio Interfaces, Reference Monitors & Soundproofing",
    ownerName: "Gurpreet Singh",
    email: "gurpreet@soundmaster.in",
    password: "Vendor@123",
    mobile: "9814012345",
    businessAddress: "56, Sector 34-A, Sub City Centre",
    location: "Chandigarh, Punjab",
    joinedDate: "2024-09-05",
    avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=120&h=120&fit=crop",
    banner: "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=1200&h=300&fit=crop",
    themeColor: "#9333EA",
    themePreset: "violet",
    storeStatus: "published",
    isVerified: true,
    gstin: "03AABCS7890Q6Z7",
    announcement: "🎙️ Authorised Indian Distributor for Professional Recording Gear & Microphones.",
    featuredProductIds: ["p136", "p137", "p138", "p139"],
    storeRating: 4.9,
    totalOrdersFulfilled: 21,
    onTimeDispatchRate: "99.3%",
    shippingPartners: ["BlueDart Express", "Delhivery Surface", "DTDC Air"],
    returnPolicy: "7 Days Physical Replacement for Technical Defects",
    warrantyPolicy: "2-Year Direct Importer Warranty & Official Tax Invoice",
    description: "SoundMaster Pro Audio supplies verified studio condenser microphones, reference monitors, and acoustic solutions for podcasters, musicians, and creators."
  }
];

// Helper to construct reviews
const makeReviews = (sku, pName) => [
  {
    id: `rev-${sku}-1`,
    customerName: "Arun Mehta",
    rating: 5,
    title: "100% Genuine product & ultra-fast delivery!",
    comment: `Received ${pName} in original factory sealed box with GST tax invoice. Verified on brand website without issue.`,
    date: "2024-09-02",
    verified: true
  },
  {
    id: `rev-${sku}-2`,
    customerName: "Neha Singh",
    rating: 5,
    title: "Outstanding merchant packaging",
    comment: "Triple bubble wrapped outer carton and priority courier tracking via BlueDart. Highly recommended seller!",
    date: "2024-09-10",
    verified: true
  },
  {
    id: `rev-${sku}-3`,
    customerName: "Siddharth Verma",
    rating: 4,
    title: "Excellent build quality",
    comment: "Performance matches description exactly. Great customer support from merchant when tracking delivery.",
    date: "2024-09-14",
    verified: true
  }
];

const makeInquiries = (sku, pName, vName) => [
  {
    id: `qa-${sku}-1`,
    customerName: "Kavita Rao",
    date: "2024-09-01",
    question: `Does this physical item come with manufacturer warranty valid across service centers in India?`,
    answer: `Yes! Every unit dispatched by ${vName} is 100% authentic with valid brand warranty card and GST invoice for doorstep service.`,
    answeredAt: "2024-09-01"
  }
];

export { vendors, makeReviews, makeInquiries };
