import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// ── 10 Realistic Indian Physical Merchants (v11 to v20) ──────────────────
export const newVendors = [
  {
    id: "v11",
    businessName: "ChaiCulture & Spices Heritage",
    storeSlug: "chaiculture",
    tagline: "Single-Estate Darjeeling Teas, Assam Orthodox Blends & Malabar GI-Tagged Spices",
    ownerName: "Vikramaditya Roy",
    email: "vikram@chaiculture.in",
    password: "Vendor@123",
    mobile: "9830198765",
    businessAddress: "28, Park Street, Camac Street Crossing",
    location: "Kolkata, West Bengal",
    joinedDate: "2024-03-12",
    avatar: "https://images.unsplash.com/photo-1544717305-2782549b5136?w=120&h=120&fit=crop",
    banner: "https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=1200&h=300&fit=crop",
    themeColor: "#D97706",
    themePreset: "amber",
    storeStatus: "published",
    isVerified: true,
    gstin: "19AABCU4512D1ZX",
    announcement: "☕ Direct Garden Dispatches from Darjeeling & Assam with Nitrogen Flush Sealed Packaging.",
    featuredProductIds: ["p151", "p152", "p153", "p154"],
    storeRating: 4.9,
    totalOrdersFulfilled: 1420,
    onTimeDispatchRate: "99.1%",
    shippingPartners: ["BlueDart Express", "Delhivery Surface", "DTDC Air"],
    returnPolicy: "7 Days Freshness Guarantee - Full Replacement for Damaged Aroma Seals",
    warrantyPolicy: "100% Certified Organic & FSSAI Lab Tested Batch Reports",
    description: "ChaiCulture sources directly from heritage tea estates in Darjeeling, the Brahmaputra Valley, and Malabar spice gardens for unparalleled aroma and authenticity."
  },
  {
    id: "v12",
    businessName: "Lumina Home & Smart Lighting",
    storeSlug: "lumina",
    tagline: "Architectural Magnetic Tracks, Smart Ambient Fixtures & Nordic Minimalist Chandeliers",
    ownerName: "Sneha Singhania",
    email: "sneha@lumina.in",
    password: "Vendor@123",
    mobile: "9820543210",
    businessAddress: "Plot 42, Road No. 36, Jubilee Hills",
    location: "Hyderabad, Telangana",
    joinedDate: "2024-02-18",
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=120&h=120&fit=crop",
    banner: "https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=1200&h=300&fit=crop",
    themeColor: "#F59E0B",
    themePreset: "amber",
    storeStatus: "published",
    isVerified: true,
    gstin: "36AABCL8890K1ZW",
    announcement: "💡 Free Remote Lighting Design Consultations with Certified Illuminating Engineers.",
    featuredProductIds: ["p161", "p162", "p163", "p164"],
    storeRating: 4.8,
    totalOrdersFulfilled: 890,
    onTimeDispatchRate: "98.4%",
    shippingPartners: ["BlueDart Express", "Delhivery Surface"],
    returnPolicy: "10 Days Hassle-Free Replacement for Driver or Optical Module Defects",
    warrantyPolicy: "2 to 5 Years Comprehensive On-Site Warranty with Official Tax Invoice",
    description: "Lumina Studio curates architectural-grade smart illumination, CRI 95+ light engines, and high-efficiency smart LED fixtures for modern residences."
  },
  {
    id: "v13",
    businessName: "Himalayan Pure Organics",
    storeSlug: "himalayanpure",
    tagline: "Wild Forest Raw Honeys, Wood-Pressed Oils, A2 Bilona Ghee & High-Altitude Herbs",
    ownerName: "Rahul Rawat",
    email: "rahul@himalayanpure.in",
    password: "Vendor@123",
    mobile: "9816045678",
    businessAddress: "12/A, Rajpur Road, Near Jakhan",
    location: "Dehradun, Uttarakhand",
    joinedDate: "2024-01-20",
    avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=120&h=120&fit=crop",
    banner: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1200&h=300&fit=crop",
    themeColor: "#059669",
    themePreset: "emerald",
    storeStatus: "published",
    isVerified: true,
    gstin: "05AABCH9912M1Z5",
    announcement: "🌿 Harvested sustainably at 6,500+ ft altitude with zero chemical processing.",
    featuredProductIds: ["p171", "p172", "p173", "p174"],
    storeRating: 4.9,
    totalOrdersFulfilled: 2150,
    onTimeDispatchRate: "99.5%",
    shippingPartners: ["Delhivery Surface", "BlueDart Express", "India Post Air"],
    returnPolicy: "7 Days Replacement for Broken Glass Containers or Seal Tampering",
    warrantyPolicy: "100% Raw Unpasteurized Guarantee with Nuclear Magnetic Resonance (NMR) Lab Reports",
    description: "Himalayan Pure Organics works with Uttarakhand self-help farmer collectives to bring mountain produce directly to discerning households nationwide."
  },
  {
    id: "v14",
    businessName: "Aethelgard Leather Works",
    storeSlug: "aethelgard",
    tagline: "Full-Grain Vegetable Tanned Bags, Laptop Messengers & Handcrafted Everyday Carry",
    ownerName: "Kabir Kapoor",
    email: "kabir@aethelgard.in",
    password: "Vendor@123",
    mobile: "9821167890",
    businessAddress: "78, Civil Lines, Near Parade Square",
    location: "Kanpur, Uttar Pradesh",
    joinedDate: "2024-04-05",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&h=120&fit=crop",
    banner: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=1200&h=300&fit=crop",
    themeColor: "#78350F",
    themePreset: "slate",
    storeStatus: "published",
    isVerified: true,
    gstin: "09AABCA7766L1ZQ",
    announcement: "🎒 Lifetime Stitching & Hardware Guarantee on All Full-Grain Buffalo Leather Bags.",
    featuredProductIds: ["p181", "p182", "p183", "p184"],
    storeRating: 4.8,
    totalOrdersFulfilled: 980,
    onTimeDispatchRate: "98.7%",
    shippingPartners: ["BlueDart Express", "Delhivery Surface"],
    returnPolicy: "15 Days Physical Return or Size Exchange with Complimentary Reverse Pickup",
    warrantyPolicy: "Lifetime Stitching & Solid Brass Hardware Warranty",
    description: "Master leathercrafters in Kanpur building heirloom-grade leather gear that ages gracefully with a rich patina over decades of daily adventures."
  },
  {
    id: "v15",
    businessName: "Apex Pro Fitness & Strength Lab",
    storeSlug: "apexfitness",
    tagline: "Commercial Olympic Barbells, Heavy-Duty Racks & High-Density Bumper Plates",
    ownerName: "Harpreet Brar",
    email: "harpreet@apexfitness.in",
    password: "Vendor@123",
    mobile: "9872054321",
    businessAddress: "B-XXII, Ferozepur Road, Gurdev Nagar",
    location: "Ludhiana, Punjab",
    joinedDate: "2024-02-10",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&h=120&fit=crop",
    banner: "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=1200&h=300&fit=crop",
    themeColor: "#DC2626",
    themePreset: "rose",
    storeStatus: "published",
    isVerified: true,
    gstin: "03AABCA2233P1ZR",
    announcement: "🏋️ Heavy-duty pallet freight dispatch across India with drop-test safety certifications.",
    featuredProductIds: ["p191", "p192", "p193", "p194"],
    storeRating: 4.9,
    totalOrdersFulfilled: 1120,
    onTimeDispatchRate: "98.9%",
    shippingPartners: ["Delhivery Heavy Freight", "Gati KWE", "BlueDart Express"],
    returnPolicy: "10 Days Component Replacement for Manufacturing Flaws or Knurling Imperfections",
    warrantyPolicy: "5-Year Barbell Shaft Warranty & 2-Year Frame Structural Warranty",
    description: "Apex Pro manufactures professional strength training gear engineered to IPF and IWF tolerances for commercial fitness centers and home gyms."
  },
  {
    id: "v16",
    businessName: "Kaveri Handlooms & Silks",
    storeSlug: "kaverisilks",
    tagline: "GI-Certified Pure Kanchipuram Silks, Tussar Weaves & Handloom Linen Essentials",
    ownerName: "Meenakshi Sundaram",
    email: "meenakshi@kaverisilks.in",
    password: "Vendor@123",
    mobile: "9840187654",
    businessAddress: "112, Gandhi Road, Temple Town",
    location: "Kanchipuram, Tamil Nadu",
    joinedDate: "2024-01-08",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=120&h=120&fit=crop",
    banner: "https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=1200&h=300&fit=crop",
    themeColor: "#BE185D",
    themePreset: "rose",
    storeStatus: "published",
    isVerified: true,
    gstin: "33AABCK6655J1ZX",
    announcement: "🥻 Silk Mark India Certified 100% Pure Mulberry Silk & Handwoven Real Silver Zari.",
    featuredProductIds: ["p201", "p202", "p203", "p204"],
    storeRating: 4.9,
    totalOrdersFulfilled: 1670,
    onTimeDispatchRate: "99.4%",
    shippingPartners: ["BlueDart Express", "DTDC Air"],
    returnPolicy: "7 Days Return Policy with Silk Mark Tag Untampered",
    warrantyPolicy: "Official Silk Mark & Handloom Mark Tag Authenticated",
    description: "Kaveri Silks preserves centuries-old weaving traditions from master looms in Kanchipuram and Arani with authenticated Silk Mark verification."
  },
  {
    id: "v17",
    businessName: "AutoCraft Pro Accessories",
    storeSlug: "autocraft",
    tagline: "4K Dual Dash Cams, High-Flow Inflators, Jump Starters & Ceramic Auto Detailing",
    ownerName: "Gaurav Malhotra",
    email: "gaurav@autocraft.in",
    password: "Vendor@123",
    mobile: "9811122334",
    businessAddress: "Shop 18, Sector 14 Main Market",
    location: "Gurugram, Haryana",
    joinedDate: "2024-03-01",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&h=120&fit=crop",
    banner: "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=1200&h=300&fit=crop",
    themeColor: "#0284C7",
    themePreset: "indigo",
    storeStatus: "published",
    isVerified: true,
    gstin: "06AABCA3344R1ZS",
    announcement: "🚗 Direct Importer of Flagship STARVIS 2 Night Vision Dash Cams & Tyre Systems.",
    featuredProductIds: ["p211", "p212", "p213", "p214"],
    storeRating: 4.8,
    totalOrdersFulfilled: 1350,
    onTimeDispatchRate: "99.0%",
    shippingPartners: ["BlueDart Express", "Delhivery Surface", "DTDC Air"],
    returnPolicy: "7 Days Replacement for Electronic or Pressure Calibration Faults",
    warrantyPolicy: "1-Year Direct Brand Warranty with Official Indian Tax Invoices",
    description: "AutoCraft Pro equips car owners with essential automotive tech, intelligent dashcams, emergency battery packs, and detailing solutions."
  },
  {
    id: "v18",
    businessName: "NourishBotanica Ayurveda",
    storeSlug: "nourishbotanica",
    tagline: "Clinical Botanical Skincare, Kumkumadi Elixirs & Cold-Pressed Kerala Hair Tonics",
    ownerName: "Dr. Ananya Nambiar",
    email: "ananya@nourishbotanica.in",
    password: "Vendor@123",
    mobile: "9845012398",
    businessAddress: "Door 45/182, Panampilly Nagar Main Ave",
    location: "Kochi, Kerala",
    joinedDate: "2024-02-14",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&h=120&fit=crop",
    banner: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=1200&h=300&fit=crop",
    themeColor: "#16A34A",
    themePreset: "emerald",
    storeStatus: "published",
    isVerified: true,
    gstin: "32AABCN5544K1ZV",
    announcement: "✨ Formulated with Kerala AYUSH-Licensed Botanical Decoctions & Saffron Extracts.",
    featuredProductIds: ["p221", "p222", "p223", "p224"],
    storeRating: 4.9,
    totalOrdersFulfilled: 2450,
    onTimeDispatchRate: "99.6%",
    shippingPartners: ["BlueDart Express", "Delhivery Surface", "DTDC Air"],
    returnPolicy: "7 Days Replacement for Breakage or Seal Damage during transit",
    warrantyPolicy: "100% Ayurvedic Pharmacopoeia Standards & Dermatologist Clinically Tested",
    description: "Doctor-formulated Ayurvedic skin and scalp remedies crafted with classical decoctions, cold-pressed herbs, and natural essential oils."
  },
  {
    id: "v19",
    businessName: "Crestview Premium Eyewear",
    storeSlug: "crestview",
    tagline: "Japanese Titanium Spectacles, Polarized TR90 Sunglasses & Blue-Cut Optics",
    ownerName: "Amit Trivedi",
    email: "amit@crestview.in",
    password: "Vendor@123",
    mobile: "9825098712",
    businessAddress: "G-4, Silver Square, Athwa Lines",
    location: "Surat, Gujarat",
    joinedDate: "2024-03-20",
    avatar: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=120&h=120&fit=crop",
    banner: "https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=1200&h=300&fit=crop",
    themeColor: "#2563EB",
    themePreset: "indigo",
    storeStatus: "published",
    isVerified: true,
    gstin: "24AABCC1122D1ZT",
    announcement: "👓 Complimentary Blue-Cut Screen Coating & Premium Hard Travel Case Included.",
    featuredProductIds: ["p231", "p232", "p233", "p234"],
    storeRating: 4.8,
    totalOrdersFulfilled: 1220,
    onTimeDispatchRate: "98.8%",
    shippingPartners: ["BlueDart Express", "Delhivery Surface"],
    returnPolicy: "14 Days Hassle-Free Frame Fit Exchange with Reverse Pickup",
    warrantyPolicy: "1-Year Frame Hinge & Coating Delamination Warranty",
    description: "Crestview crafts ultralight beta-titanium and Italian Mazzucchelli acetate spectacles paired with distortion-free optical coatings."
  },
  {
    id: "v20",
    businessName: "Artisanal Brew & Barware Studio",
    storeSlug: "artisanalbrew",
    tagline: "Specialty Pour-Overs, Precision Hand Grinders & Hand-Blown Whiskey Crystal",
    ownerName: "Siddharth Sengupta",
    email: "siddharth@artisanalbrew.in",
    password: "Vendor@123",
    mobile: "9831076543",
    businessAddress: "Plot 104, Saheed Nagar, Janpath Road",
    location: "Bhubaneswar, Odisha",
    joinedDate: "2024-04-10",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=120&h=120&fit=crop",
    banner: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=1200&h=300&fit=crop",
    themeColor: "#D97706",
    themePreset: "amber",
    storeStatus: "published",
    isVerified: true,
    gstin: "21AABCA8877E1ZX",
    announcement: "☕ Master the perfect extraction with barista-grade stainless steel & crystal tools.",
    featuredProductIds: ["p241", "p242", "p243", "p244"],
    storeRating: 4.9,
    totalOrdersFulfilled: 1540,
    onTimeDispatchRate: "99.2%",
    shippingPartners: ["BlueDart Express", "Delhivery Surface", "DTDC Air"],
    returnPolicy: "7 Days Free Replacement for Glassware Breakage or Calibration Issues",
    warrantyPolicy: "2-Year Burrs & Mechanical Warranty on Precision Grinders",
    description: "Artisanal Brew supplies specialty coffee gear, pour-over equipment, burr grinders, and lead-free crystal barware to connoisseurs across India."
  }
];

// ── 100 Realistic Products (10 per vendor: p151 to p250) ──────────────────
export const newProducts = [
  // v11: ChaiCulture (p151 - p160)
  {
    id: "p151",
    sku: "VM-TEA-P151-DAR",
    name: "Darjeeling First Flush FTGFOP1 Whole Leaf Tea",
    category: "Grocery",
    brand: "ChaiCulture Heritage",
    price: 1250,
    mrp: 1499,
    discountPercent: 17,
    stock: 45,
    quantity: 45,
    barcode: "8901000001511",
    lowStockThreshold: 10,
    reservedStock: 0,
    warehouseLocation: "Aisle T-1",
    restockLeadDays: 4,
    vendorId: "v11",
    status: "approved",
    images: [
      "https://images.unsplash.com/photo-1597481499750-3e6b22637e12?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=600&h=600&fit=crop"
    ],
    description: "Hand-plucked spring harvest from high-elevation Darjeeling slopes. Exhibits bright floral muscatel notes with an amber liquor.",
    condition: "Brand New (Sealed)",
    specifications: { "Grade": "FTGFOP1", "Flush": "First Flush (Spring)", "Weight": "250 g", "Packaging": "Aroma Lock Tin Caddy", "Caffeine": "Medium" },
    shipping: { weight: "380 g", dispatchTime: "Ships within 24 hours", estimatedDays: "2 - 4 days", courierPartners: ["BlueDart Express", "Delhivery Surface"], codAvailable: true, returnWindowDays: 7 },
    variants: { colors: [{ name: "Amber Gold", hex: "#D97706", inStock: true }], options: [{ label: "250g Caddy", priceDelta: 0, stock: 45 }] },
    badge: "Bestseller",
    tags: ["darjeeling", "tea", "organic", "first flush", "chaiculture"]
  },
  {
    id: "p152",
    sku: "VM-TEA-P152-ASS",
    name: "Assam Golden Tips Orthodox Black Tea 500g",
    category: "Grocery",
    brand: "ChaiCulture Heritage",
    price: 890,
    mrp: 1099,
    discountPercent: 19,
    stock: 60,
    quantity: 60,
    barcode: "8901000001528",
    lowStockThreshold: 12,
    reservedStock: 0,
    warehouseLocation: "Aisle T-2",
    restockLeadDays: 3,
    vendorId: "v11",
    status: "approved",
    images: [
      "https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1597481499750-3e6b22637e12?w=600&h=600&fit=crop"
    ],
    description: "Robust, malty breakfast tea with rich golden tips grown in the Upper Assam floodplains. Perfect with a splash of milk.",
    condition: "Brand New (Sealed)",
    specifications: { "Origin": "Upper Assam", "Weight": "500 g", "Leaf Style": "Orthodox Broken Orange Pekoe", "Best Before": "24 Months" },
    shipping: { weight: "620 g", dispatchTime: "Ships within 24 hours", estimatedDays: "2 - 4 days", courierPartners: ["BlueDart Express", "Delhivery Surface"], codAvailable: true, returnWindowDays: 7 },
    variants: { colors: [{ name: "Deep Ruby", hex: "#7F1D1D", inStock: true }], options: [{ label: "500g Stand-up Pouch", priceDelta: 0, stock: 60 }] },
    badge: "Staff Pick",
    tags: ["assam", "black tea", "malty", "breakfast tea"]
  },
  {
    id: "p153",
    sku: "VM-TEA-P153-CRD",
    name: "Alleppey Green Cardamom 8mm Bold Grade 200g",
    category: "Grocery",
    brand: "Malabar Heritage",
    price: 950,
    mrp: 1200,
    discountPercent: 21,
    stock: 35,
    quantity: 35,
    barcode: "8901000001535",
    lowStockThreshold: 8,
    reservedStock: 0,
    warehouseLocation: "Aisle S-1",
    restockLeadDays: 4,
    vendorId: "v11",
    status: "approved",
    images: [
      "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&h=600&fit=crop"
    ],
    description: "GI-tagged giant 8mm extra bold green cardamom pods hand-picked from the Western Ghats of Idukki. Intense aroma and essential oil density.",
    condition: "Brand New (Sealed)",
    specifications: { "Pod Size": "8 mm+ Extra Bold", "Origin": "Idukki, Kerala", "Moisture": "<10%", "Weight": "200 g" },
    shipping: { weight: "280 g", dispatchTime: "Ships within 24 hours", estimatedDays: "2 - 4 days", courierPartners: ["BlueDart Express", "DTDC Air"], codAvailable: true, returnWindowDays: 7 },
    variants: { colors: [{ name: "Forest Green", hex: "#15803D", inStock: true }], options: [{ label: "200g Vacuum Pouch", priceDelta: 0, stock: 35 }] },
    badge: "GI Tagged",
    tags: ["cardamom", "spices", "kerala", "alleppey"]
  },
  {
    id: "p154",
    sku: "VM-TEA-P154-PEP",
    name: "Wayanad Tellicherry Garbled Extra Bold Black Pepper 250g",
    category: "Grocery",
    brand: "Malabar Heritage",
    price: 499,
    mrp: 650,
    discountPercent: 23,
    stock: 80,
    quantity: 80,
    barcode: "8901000001542",
    lowStockThreshold: 15,
    reservedStock: 0,
    warehouseLocation: "Aisle S-2",
    restockLeadDays: 3,
    vendorId: "v11",
    status: "approved",
    images: [
      "https://images.unsplash.com/photo-1509358271058-acd22cc93898?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=600&h=600&fit=crop"
    ],
    description: "The world's highest grade peppercorn (TGSEB). Sun-dried black pepper berries with complex citrus-pine warmth and high piperine index.",
    condition: "Brand New (Sealed)",
    specifications: { "Grade": "TGSEB (Tellicherry Garbled Extra Bold)", "Size": "4.75mm+", "Weight": "250 g", "Origin": "Wayanad, Kerala" },
    shipping: { weight: "320 g", dispatchTime: "Ships within 24 hours", estimatedDays: "2 - 4 days", courierPartners: ["BlueDart Express", "Delhivery Surface"], codAvailable: true, returnWindowDays: 7 },
    variants: { colors: [{ name: "Jet Black", hex: "#18181B", inStock: true }], options: [{ label: "250g Jar", priceDelta: 0, stock: 80 }] },
    badge: "Verified Indian Brand",
    tags: ["pepper", "tellicherry", "wayanad", "spices"]
  },
  {
    id: "p155",
    sku: "VM-TEA-P155-SAF",
    name: "Kashmiri Mogra Saffron (Kesar) 2g Certified Grade A1",
    category: "Grocery",
    brand: "ChaiCulture Heritage",
    price: 999,
    mrp: 1350,
    discountPercent: 26,
    stock: 25,
    quantity: 25,
    barcode: "8901000001559",
    lowStockThreshold: 5,
    reservedStock: 0,
    warehouseLocation: "Vault V-1",
    restockLeadDays: 5,
    vendorId: "v11",
    status: "approved",
    images: [
      "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=600&h=600&fit=crop"
    ],
    description: "Pure Pampore saffron crimson stigmata without yellow styles. Delivers golden color, intoxicating floral fragrance, and natural antioxidant potency.",
    condition: "Brand New (Sealed)",
    specifications: { "Origin": "Pampore, Kashmir", "Net Weight": "2 g", "Grade": "Mogra Grade 1", "Packaging": "Airtight Acrylic Capsule" },
    shipping: { weight: "120 g", dispatchTime: "Ships within 24 hours", estimatedDays: "2 - 3 days", courierPartners: ["BlueDart Express", "DTDC Air"], codAvailable: false, returnWindowDays: 7 },
    variants: { colors: [{ name: "Deep Saffron", hex: "#EA580C", inStock: true }], options: [{ label: "2g Glass Vial", priceDelta: 0, stock: 25 }] },
    badge: "Pure Saffron",
    tags: ["saffron", "kesar", "kashmir", "luxury"]
  },
  {
    id: "p156",
    sku: "VM-TEA-P156-NIL",
    name: "Nilgiri Winter Frost White Tea 100g",
    category: "Grocery",
    brand: "ChaiCulture Heritage",
    price: 1100,
    mrp: 1400,
    discountPercent: 21,
    stock: 30,
    quantity: 30,
    barcode: "8901000001566",
    lowStockThreshold: 6,
    reservedStock: 0,
    warehouseLocation: "Aisle T-3",
    restockLeadDays: 4,
    vendorId: "v11",
    status: "approved",
    images: [
      "https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1597481499750-3e6b22637e12?w=600&h=600&fit=crop"
    ],
    description: "Rare silver needles harvested during freezing winter mornings at 7,000 feet in Coonoor. Notes of honeydew melon and white peach.",
    condition: "Brand New (Sealed)",
    specifications: { "Altitude": "7,000 ft", "Type": "Silver Needle White Tea", "Weight": "100 g", "Harvest": "Winter Frost" },
    shipping: { weight: "220 g", dispatchTime: "Ships within 24 hours", estimatedDays: "2 - 4 days", courierPartners: ["BlueDart Express", "DTDC Air"], codAvailable: true, returnWindowDays: 7 },
    variants: { colors: [{ name: "Silver Mint", hex: "#E2E8F0", inStock: true }], options: [{ label: "100g Tin", priceDelta: 0, stock: 30 }] },
    badge: "Rare Harvest",
    tags: ["white tea", "nilgiri", "silver needle"]
  },
  {
    id: "p157",
    sku: "VM-TEA-P157-MAS",
    name: "Royal Kadak Masala Chai Blend with Real Spices 500g",
    category: "Grocery",
    brand: "ChaiCulture Heritage",
    price: 450,
    mrp: 550,
    discountPercent: 18,
    stock: 90,
    quantity: 90,
    barcode: "8901000001573",
    lowStockThreshold: 20,
    reservedStock: 0,
    warehouseLocation: "Aisle T-4",
    restockLeadDays: 2,
    vendorId: "v11",
    status: "approved",
    images: [
      "https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=600&h=600&fit=crop"
    ],
    description: "Granular CTC blended with crushed green cardamom, ginger, cinnamon, clove, and nutmeg. Yields a rich spiced dhaba-style cup.",
    condition: "Brand New (Sealed)",
    specifications: { "Spices": "Cardamom, Ginger, Clove, Cinnamon, Black Pepper", "Base": "Assam CTC", "Weight": "500 g" },
    shipping: { weight: "580 g", dispatchTime: "Ships within 24 hours", estimatedDays: "2 - 4 days", courierPartners: ["BlueDart Express", "Delhivery Surface"], codAvailable: true, returnWindowDays: 7 },
    variants: { colors: [{ name: "Rich Cinnamon", hex: "#9A3412", inStock: true }], options: [{ label: "500g Pouch", priceDelta: 0, stock: 90 }] },
    badge: "Popular Daily Pick",
    tags: ["masala chai", "tea", "assam ctc", "spiced tea"]
  },
  {
    id: "p158",
    sku: "VM-TEA-P158-TUL",
    name: "Organic Whole Leaf Green Tea with Rama & Krishna Tulsi 250g",
    category: "Grocery",
    brand: "ChaiCulture Heritage",
    price: 520,
    mrp: 650,
    discountPercent: 20,
    stock: 55,
    quantity: 55,
    barcode: "8901000001580",
    lowStockThreshold: 10,
    reservedStock: 0,
    warehouseLocation: "Aisle T-5",
    restockLeadDays: 3,
    vendorId: "v11",
    status: "approved",
    images: [
      "https://images.unsplash.com/photo-1597481499750-3e6b22637e12?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=600&h=600&fit=crop"
    ],
    description: "Non-bitter steamed green tea leaves paired with sacred Rama and Krishna Tulsi herbs for immunity, relaxation, and digestion.",
    condition: "Brand New (Sealed)",
    specifications: { "Certification": "USDA Organic & India Organic", "Weight": "250 g", "Brew Time": "3 Mins", "Antioxidants": "High EGCG" },
    shipping: { weight: "340 g", dispatchTime: "Ships within 24 hours", estimatedDays: "2 - 4 days", courierPartners: ["BlueDart Express", "Delhivery Surface"], codAvailable: true, returnWindowDays: 7 },
    variants: { colors: [{ name: "Leaf Green", hex: "#16A34A", inStock: true }], options: [{ label: "250g Foil Canister", priceDelta: 0, stock: 55 }] },
    badge: "100% Organic",
    tags: ["green tea", "tulsi", "detox", "immunity"]
  },
  {
    id: "p159",
    sku: "VM-TEA-P159-CIN",
    name: "Ceylon True Cinnamon Quills (Sri Lankan Dalchini) 150g",
    category: "Grocery",
    brand: "Malabar Heritage",
    price: 399,
    mrp: 520,
    discountPercent: 23,
    stock: 70,
    quantity: 70,
    barcode: "8901000001597",
    lowStockThreshold: 12,
    reservedStock: 0,
    warehouseLocation: "Aisle S-3",
    restockLeadDays: 3,
    vendorId: "v11",
    status: "approved",
    images: [
      "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1509358271058-acd22cc93898?w=600&h=600&fit=crop"
    ],
    description: "Authentic paper-thin layered Alba-grade Ceylon cinnamon sticks. Ultra-low coumarin content, sweet woody fragrance, safe for daily baking and tea.",
    condition: "Brand New (Sealed)",
    specifications: { "Type": "Cinnamomum Verum (True Cinnamon)", "Origin": "Single Estate", "Weight": "150 g", "Coumarin": "<0.004%" },
    shipping: { weight: "240 g", dispatchTime: "Ships within 24 hours", estimatedDays: "2 - 4 days", courierPartners: ["BlueDart Express", "Delhivery Surface"], codAvailable: true, returnWindowDays: 7 },
    variants: { colors: [{ name: "Woody Tan", hex: "#B45309", inStock: true }], options: [{ label: "150g Zip Pouch", priceDelta: 0, stock: 70 }] },
    badge: "Low Coumarin",
    tags: ["cinnamon", "dalchini", "ceylon", "spices"]
  },
  {
    id: "p160",
    sku: "VM-TEA-P160-GFT",
    name: "Grand Heritage Indian Tea Connoisseur Gift Chest (4 Luxury Tins)",
    category: "Grocery",
    brand: "ChaiCulture Heritage",
    price: 2499,
    mrp: 3200,
    discountPercent: 22,
    stock: 20,
    quantity: 20,
    barcode: "8901000001603",
    lowStockThreshold: 5,
    reservedStock: 0,
    warehouseLocation: "Gift Vault G-1",
    restockLeadDays: 5,
    vendorId: "v11",
    status: "approved",
    images: [
      "https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1597481499750-3e6b22637e12?w=600&h=600&fit=crop"
    ],
    description: "Artisanal handcrafted pine wood chest containing 4 airtight embossed caddies: Darjeeling First Flush, Assam Golden Tips, Kashmiri Kahwa, and Nilgiri Oolong.",
    condition: "Brand New (Sealed)",
    specifications: { "Chest Material": "Polished Natural Pine Wood", "Contents": "4 x 75g Tins", "Accessories": "Brass Tea Infuser Spoon Included" },
    shipping: { weight: "1250 g", dispatchTime: "Ships within 24 hours", estimatedDays: "2 - 4 days", courierPartners: ["BlueDart Express", "DTDC Air"], codAvailable: true, returnWindowDays: 7 },
    variants: { colors: [{ name: "Teak & Brass", hex: "#78350F", inStock: true }], options: [{ label: "Deluxe Wooden Chest", priceDelta: 0, stock: 20 }] },
    badge: "Luxury Gift Set",
    tags: ["gift", "luxury tea", "assortment", "wooden chest"]
  }
];
