import { createContext, useContext, useState, useEffect, useCallback, useMemo } from 'react';

export const LANGUAGES = [
  { code: 'en', name: 'English', native: 'English', flag: '🇬🇧' },
  { code: 'ta', name: 'Tamil', native: 'தமிழ்', flag: '🇮🇳' },
  { code: 'ml', name: 'Malayalam', native: 'മലയാളം', flag: '🇮🇳' },
  { code: 'te', name: 'Telugu', native: 'తెలుగు', flag: '🇮🇳' },
  { code: 'kn', name: 'Kannada', native: 'ಕನ್ನಡ', flag: '🇮🇳' },
  { code: 'hi', name: 'Hindi', native: 'हिन्दी', flag: '🇮🇳' },
];

export const TRANSLATIONS = {
  en: {
    // Topbar & Nav
    platformTag: 'Vendor Hub — Multi-Vendor Marketplace',
    customerShop: 'Customer Shop',
    vendorPortal: 'Vendor Portal',
    adminPortal: 'Admin Portal',
    searchPlaceholder: 'Search products, brands, categories...',
    cart: 'Cart',
    orders: 'Orders',
    compare: 'Compare',
    profile: 'Profile',
    logout: 'Sign Out',
    login: 'Sign In',
    register: 'Register',
    theme: 'Theme',
    language: 'Language',

    // Categories
    cat_all: 'All',
    cat_electronics: 'Electronics',
    cat_fashion: 'Fashion',
    cat_grocery: 'Grocery',
    cat_home: 'Home & Living',
    cat_sports: 'Sports',
    cat_beauty: 'Beauty',

    // Product Listing & Filters
    marketplaceCatalog: 'Marketplace Catalog',
    verifiedLocalProducts: 'verified local vendor products in stock & ready for physical dispatch',
    allCategories: 'All Categories',
    filterBy: 'Filters',
    sortBy: 'Sort By',
    sort_newest: 'Newest Arrivals',
    sort_price_asc: 'Price: Low to High',
    sort_price_desc: 'Price: High to Low',
    sort_rating: 'Top Customer Rated',
    inStockOnly: 'In Stock Only',
    fastDeliveryOnly: 'Fast Dispatch (24h)',
    resetFilters: 'Reset Filters',
    addToCart: 'Add to Cart',
    addedToCart: 'Added to Cart',
    viewProduct: 'View Details',
    freeShipping: 'Free Shipping',
    codAvailable: 'Cash on Delivery Available',
    inStock: 'In Stock',
    lowStock: 'Low Stock',
    outOfStock: 'Out of Stock',
    unitsLeft: 'units left',

    // Cart & Checkout
    shoppingCart: 'Shopping Cart',
    cartItemsCount: 'physical items in your cart',
    cartEmpty: 'Your Cart is Currently Empty',
    cartEmptyDesc: 'Explore our catalog to add electronics, fashion, groceries, and home goods.',
    exploreCatalog: 'Explore Catalog',
    orderSummary: 'Order Summary',
    subtotal: 'Items Subtotal',
    courierShipping: 'Courier Shipping',
    totalAmount: 'Total Amount',
    deliveryAddress: 'Physical Delivery Destination',
    recipientName: 'Recipient Full Name',
    mobilePhone: 'Mobile Phone',
    pincode: 'Postal Pincode',
    streetAddress: 'Street Address / Flat / Floor',
    city: 'City',
    state: 'State',
    courierMethod: 'Courier Dispatch Method',
    standardShipping: 'Delhivery Surface Express',
    expressShipping: 'BlueDart Priority Air',

    // Payment Options
    paymentOptions: 'Payment Options',
    paymentMethod: 'Payment Method',
    payUpiQr: 'UPI & QR Code',
    payUpiQrSubtitle: 'Instant 0 Fee',
    payCod: 'Cash on Delivery',
    payCodSubtitle: 'Pay at Doorstep',
    payCards: 'Cards / Banking',
    payCardsSubtitle: 'Visa, RuPay, MC',
    scanToPay: 'Scan & Pay via any UPI App',
    qrValidFor: 'QR valid for',
    simulateQrPay: 'Simulate QR Scan & Verify Payment',
    verifyingGateway: 'Verifying with UPI Bank Gateway...',
    upiVerifiedSuccess: 'UPI Payment Received & Verified!',
    orEnterUpiId: 'Or enter your UPI ID (e.g. user@oksbi)',
    payViaUpiApp: 'Pay via UPI App',
    codEligible: 'ELIGIBLE FOR FREE COD',
    codNotice: 'Pay with Cash or Courier UPI QR upon doorstep arrival.',
    codOtpTitle: 'Tamper-Proof Delivery OTP',
    codOtpNotice: 'A 4-digit security code will be generated upon placing this order. Share it with the delivery executive only after verifying the package.',
    codAgreement: 'I agree to keep the exact amount ready at delivery and inspect the outer carton before sharing OTP.',
    placeCodOrder: 'Confirm Cash on Delivery Order',
    placeUpiOrder: 'Place Physical Order via UPI QR',
    placeCardOrder: 'Pay & Place Physical Order',

    // Order Success
    orderPlacedSuccess: 'Order Placed Successfully!',
    doorstepOtpCode: 'Doorstep Delivery OTP',
    courierPartner: 'COURIER PARTNER',
    trackingNumber: 'TRACKING NUMBER',
    paymentStatus: 'PAYMENT STATUS',
    paidStatus: 'PAID',
    codPendingStatus: 'Pending (Pay on Delivery)',
    viewTrackOrders: 'View & Track My Orders',
    continueShopping: 'Continue Shopping',

    // Orders Page
    myOrdersTitle: 'My Orders & Physical Tracking',
    filterAll: 'All Orders',
    filterPlaced: 'Stock Reserved',
    filterConfirmed: 'Packaging Verified',
    filterDispatched: 'In Transit',
    filterDelivered: 'Delivered',
    raiseDispute: 'Raise Dispute',
    trackShipment: 'Track Shipment',
    hideTracking: 'Hide Tracking',
    rateProduct: 'Rate Product',
    supportTicket: 'Support Ticket',
    returnReplace: 'Return / Replace',

    // Theme Customizer
    themeCustomizerTitle: 'Customize Platform Theme',
    themeCustomizerDesc: 'Personalize your visual experience with curated light, bright, and vibrant palettes.',
    themePreset: 'Theme Preset',
    themeClassicLight: 'Classic Light',
    themeClassicLightDesc: 'Clean, modern slate with indigo primary',
    themeBrightElectric: 'Bright Electric',
    themeBrightElectricDesc: 'High-luminance crisp white with electric violet & cyan',
    themeBrightSunburst: 'Bright Sunburst',
    themeBrightSunburstDesc: 'Warm golden citrus surfaces with radiant amber',
    themeBrightEmerald: 'Bright Emerald',
    themeBrightEmeraldDesc: 'Fresh mint & organic emerald green accents',
    themeMidnightDark: 'Midnight Dark',
    themeMidnightDarkDesc: 'Deep contrast dark theme with vibrant neon highlights',
    accentColor: 'Accent Color',
    brightnessLevel: 'Brightness Level',
    normalBrightness: 'Normal Bright',
    highBrightness: 'Ultra Bright Glow',
    resetTheme: 'Reset to Defaults',
  },

  ta: {
    // Tamil (தமிழ்)
    platformTag: 'வெண்டர் ஹப் — பல வணிகர் சந்தை',
    customerShop: 'வாடிக்கையாளர் அங்காடி',
    vendorPortal: 'வணிகர் தளம்',
    adminPortal: 'நிர்வாக தளம்',
    searchPlaceholder: 'தயாரிப்புகள், பிராண்டுகள், வகைகளைத் தேடுக...',
    cart: 'கூடை',
    orders: 'ஆர்டர்கள்',
    compare: 'ஒப்பீடு',
    profile: 'சுயவிவரம்',
    logout: 'வெளியேறு',
    login: 'உள்நுழைக',
    register: 'பதிவு செய்க',
    theme: 'வண்ண தோற்றம்',
    language: 'மொழி',

    // Categories
    cat_all: 'அனைத்தும்',
    cat_electronics: 'எலக்ட்ரானிக்ஸ்',
    cat_fashion: 'ஆடைகள்',
    cat_grocery: 'மளிகை பொருட்கள்',
    cat_home: 'வீடு & வாழ்க்கை',
    cat_sports: 'விளையாட்டு',
    cat_beauty: 'அழகு பொருட்கள்',

    // Product Listing & Filters
    marketplaceCatalog: 'சந்தை பட்டியல்',
    verifiedLocalProducts: 'சரிபார்க்கப்பட்ட உள்ளூர் தயாரிப்புகள் இருப்பில் உள்ளன',
    allCategories: 'அனைத்து பிரிவுகள்',
    filterBy: 'வடிகட்டிகள்',
    sortBy: 'வரிசைப்படுத்து',
    sort_newest: 'புதிய வரவுகள்',
    sort_price_asc: 'விலை: குறைந்ததிலிருந்து அதிகம்',
    sort_price_desc: 'விலை: அதிகத்திலிருந்து குறைவு',
    sort_rating: 'சிறந்த மதிப்பீடு',
    inStockOnly: 'இருப்பில் உள்ளவை மட்டும்',
    fastDeliveryOnly: 'விரைவு விநியோகம் (24 மணி)',
    resetFilters: 'வடிகட்டிகளை மீட்டமை',
    addToCart: 'கூடையில் சேர்',
    addedToCart: 'கூடையில் சேர்க்கப்பட்டது',
    viewProduct: 'விவரங்களை காண்க',
    freeShipping: 'இலவச டெலிவரி',
    codAvailable: 'பணம் செலுத்திப் பெறும் வசதி (COD)',
    inStock: 'இருப்பில் உள்ளது',
    lowStock: 'குறைந்த இருப்பு',
    outOfStock: 'இருப்பு இல்லை',
    unitsLeft: 'எண்ணிக்கை மீதம்',

    // Cart & Checkout
    shoppingCart: 'ஷாப்பிங் கூடை',
    cartItemsCount: 'கூடையில் உள்ள பொருட்கள்',
    cartEmpty: 'உங்கள் கூடை காலியாக உள்ளது',
    cartEmptyDesc: 'எலக்ட்ரானிக்ஸ், உடைகள், மளிகைப் பொருட்களைச் சேர்க்க பட்டியலை பார்க்கவும்.',
    exploreCatalog: 'பொருட்களை காண்க',
    orderSummary: 'ஆர்டர் சுருக்கம்',
    subtotal: 'பொருட்களின் துணை மொத்தம்',
    courierShipping: 'கூரியர் கட்டணம்',
    totalAmount: 'மொத்த தொகை',
    deliveryAddress: 'டெலிவரி முகவரி',
    recipientName: 'பெறுநர் முழுப் பெயர்',
    mobilePhone: 'கைபேசி எண்',
    pincode: 'அஞ்சல் குறியீடு (Pincode)',
    streetAddress: 'தெரு முகவரி / அடுக்குமாடி',
    city: 'நகரம்',
    state: 'மாநிலம்',
    courierMethod: 'கூரியர் சேவை முறை',
    standardShipping: 'டெல்லிவரி எக்ஸ்பிரஸ் (3-5 நாட்கள்)',
    expressShipping: 'ப்ளூடார்ட் ஏர் (1-2 நாட்கள்)',

    // Payment Options
    paymentOptions: 'கட்டண முறைகள்',
    paymentMethod: 'கட்டண வகை',
    payUpiQr: 'UPI & QR குறியீடு',
    payUpiQrSubtitle: 'உடனடி 0 கட்டணம்',
    payCod: 'பணம் செலுத்திப் பெறுதல் (COD)',
    payCodSubtitle: 'வீட்டு வாசலில் பணம்',
    payCards: 'கார்டுகள் / வங்கி',
    payCardsSubtitle: 'Visa, RuPay, MC',
    scanToPay: 'எந்தவொரு UPI செயலியிலும் QR ஸ்கேன் செய்து செலுத்தவும்',
    qrValidFor: 'QR செல்லும் நேரம்',
    simulateQrPay: 'QR ஸ்கேன் சரிபார்த்து உறுதி செய்',
    verifyingGateway: 'வங்கி வாயிலில் சரிபார்க்கப்படுகிறது...',
    upiVerifiedSuccess: 'UPI பணம் பெறப்பட்டு சரிபார்க்கப்பட்டது!',
    orEnterUpiId: 'அல்லது உங்கள் UPI ID உள்ளிடவும் (எ.கா: name@oksbi)',
    payViaUpiApp: 'UPI செயலி மூலம் செலுத்து',
    codEligible: 'இலவச COD தகுதியானது',
    codNotice: 'பார்சல் வரும்போது ரொக்கமாக அல்லது UPI QR ஸ்கேன் செய்து செலுத்தவும்.',
    codOtpTitle: 'பாதுகாப்பான டெலிவரி OTP',
    codOtpNotice: 'ஆர்டர் இட்டதும் 4 இலக்க பாதுகாப்பு OTP உருவாக்கப்படும். பார்சலை சரிபார்த்த பின்பே டெலிவரி நபரிடம் பகிரவும்.',
    codAgreement: 'பார்சலை சரிபார்த்து, சரியான தொகையைத் தந்து OTP பகிர்வதை ஒப்புக்கொள்கிறேன்.',
    placeCodOrder: 'COD ஆர்டரை உறுதி செய்',
    placeUpiOrder: 'UPI QR மூலம் ஆர்டர் செய்',
    placeCardOrder: 'கார்டு மூலம் ஆர்டர் செய்',

    // Order Success
    orderPlacedSuccess: 'ஆர்டர் வெற்றிகரமாக பதிவு செய்யப்பட்டது!',
    doorstepOtpCode: 'வாசற்படி டெலிவரி OTP',
    courierPartner: 'கூரியர் பார்ட்னர்',
    trackingNumber: 'டிராக்கிங் எண்',
    paymentStatus: 'கட்டண நிலை',
    paidStatus: 'செலுத்தப்பட்டது',
    codPendingStatus: 'நிலுவையில் (டெலிவரியின்போது)',
    viewTrackOrders: 'என் ஆர்டர்களைப் பார் & டிராக் செய்',
    continueShopping: 'ஷாப்பிங்கைத் தொடரவும்',

    // Orders Page
    myOrdersTitle: 'எனது ஆர்டர்கள் & கண்காணிப்பு',
    filterAll: 'அனைத்து ஆர்டர்கள்',
    filterPlaced: 'ஆர்டர் பெறப்பட்டது',
    filterConfirmed: 'பேக்கிங் செய்யப்பட்டது',
    filterDispatched: 'வழியில் உள்ளது',
    filterDelivered: 'டெலிவரி செய்யப்பட்டது',
    raiseDispute: 'புகார் எழுப்பு',
    trackShipment: 'நேரலை கண்காணிப்பு',
    hideTracking: 'கண்காணிப்பை மறை',
    rateProduct: 'மதிப்பீடு செய்',
    supportTicket: 'உதவி டிக்கெட்',
    returnReplace: 'திரும்ப / மாற்றுக',

    // Theme Customizer
    themeCustomizerTitle: 'தளத்தின் தோற்றத்தை மாற்று',
    themeCustomizerDesc: 'பிரகாசமான, மென்மையான அல்லது தனிப்பயன் வண்ணங்களில் தளத்தை அமைத்துக் கொள்ளுங்கள்.',
    themePreset: 'தோற்ற முன்அமைப்புகள்',
    themeClassicLight: 'கிளாசிக் ஒளி (Classic Light)',
    themeClassicLightDesc: 'நேர்த்தியான தூய வெள்ளை மற்றும் நீல நிறம்',
    themeBrightElectric: 'பிரகாசமான எலக்ட்ரிக் (Bright Electric)',
    themeBrightElectricDesc: 'அதிக ஒளிரும் வெள்ளை மற்றும் ஊதா/சியான் வண்ணங்கள்',
    themeBrightSunburst: 'சூரிய ஒளிக்கதிர் (Bright Sunburst)',
    themeBrightSunburstDesc: 'சூரியனின் பொன்னிற மஞ்சள் மற்றும் ஆரஞ்சு பின்னணி',
    themeBrightEmerald: 'பச்சை மரகதம் (Bright Emerald)',
    themeBrightEmeraldDesc: 'புத்துணர்ச்சியான புதினா மற்றும் மரகதப் பச்சை',
    themeMidnightDark: 'இரவு கருமை (Midnight Dark)',
    themeMidnightDarkDesc: 'கண்களுக்கு இதமான ஆழ்ந்த கருப்பு வண்ண தோற்றம்',
    accentColor: 'முக்கிய வண்ணத் தேர்வு',
    brightnessLevel: 'பிரகாச நிலை',
    normalBrightness: 'வழக்கமான பிரகாசம்',
    highBrightness: 'அதிக பிரகாசம் (Ultra Glow)',
    resetTheme: 'மீட்டமைக்க',
  },

  ml: {
    // Malayalam (മലയാളം)
    platformTag: 'വെണ്ടർ ഹബ് — മൾട്ടി-വെണ്ടർ വിപണി',
    customerShop: 'ഉപഭോക്തൃ ഷോപ്പ്',
    vendorPortal: 'വെണ്ടർ പോർട്ടൽ',
    adminPortal: 'അഡ്മിൻ പോർട്ടൽ',
    searchPlaceholder: 'ഉൽപ്പന്നങ്ങൾ, ബ്രാൻഡുകൾ, വിഭാഗങ്ങൾ തിരയുക...',
    cart: 'കാർട്ട്',
    orders: 'ഓർഡറുകൾ',
    compare: 'താരതമ്യം',
    profile: 'പ്രൊഫൈൽ',
    logout: 'പുറത്തിറങ്ങുക',
    login: 'ലോഗിൻ',
    register: 'രജിസ്റ്റർ',
    theme: 'തീം',
    language: 'ഭാഷ',

    cat_all: 'എല്ലാം',
    cat_electronics: 'ഇലക്ട്രോണിക്സ്',
    cat_fashion: 'ഫാഷൻ',
    cat_grocery: 'പലചരക്ക്',
    cat_home: 'വീടും പരിസരവും',
    cat_sports: 'കായികം',
    cat_beauty: 'സൗന്ദര്യവർദ്ധകം',

    marketplaceCatalog: 'മാർക്കറ്റ്‌പ്ലേസ് കാറ്റലോഗ്',
    verifiedLocalProducts: 'പരിശോധിച്ചുറപ്പിച്ച പ്രാദേശിക ഉൽപ്പന്നങ്ങൾ സ്റ്റോക്കിലുണ്ട്',
    allCategories: 'എല്ലാ വിഭാഗങ്ങളും',
    filterBy: 'ഫിൽട്ടറുകൾ',
    sortBy: 'ക്രമീകരിക്കുക',
    sort_newest: 'പുതിയവ',
    sort_price_asc: 'വില: കുറഞ്ഞതിൽ നിന്ന് കൂടിയതിലേക്ക്',
    sort_price_desc: 'വില: കൂടിയതിൽ നിന്ന് കുറഞ്ഞതിലേക്ക്',
    sort_rating: 'ഉയർന്ന റേറ്റിംഗ് ഉള്ളവ',
    inStockOnly: 'സ്റ്റോക്കുള്ളവ മാത്രം',
    fastDeliveryOnly: 'വേഗതയേറിയ ഡെലിവറി (24 മണിക്കൂർ)',
    resetFilters: 'ഫിൽട്ടറുകൾ റീസെറ്റ് ചെയ്യുക',
    addToCart: 'കാർട്ടിലേക്ക് ചേർക്കുക',
    addedToCart: 'കാർട്ടിലേക്ക് ചേർത്തു',
    viewProduct: 'വിശദാംശങ്ങൾ കാണുക',
    freeShipping: 'സൗജന്യ ഷിപ്പിംഗ്',
    codAvailable: 'ക്യാഷ് ഓൺ ഡെലിവറി ലഭ്യമാണ്',
    inStock: 'സ്റ്റോക്കുണ്ട്',
    lowStock: 'കുറഞ്ഞ സ്റ്റോക്ക്',
    outOfStock: 'സ്റ്റോക്കില്ല',
    unitsLeft: 'എണ്ണം ബാക്കി',

    shoppingCart: 'ഷോപ്പിംഗ് കാർട്ട്',
    cartItemsCount: 'കാർട്ടിലുള്ള ഉൽപ്പന്നങ്ങൾ',
    cartEmpty: 'നിങ്ങളുടെ കാർട്ട് ശൂന്യമാണ്',
    cartEmptyDesc: 'ഇലക്ട്രോണിക്സ്, ഫാഷൻ, പലചരക്ക് സാധനങ്ങൾ കാർട്ടിലേക്ക് ചേർക്കൂ.',
    exploreCatalog: 'കാറ്റലോഗ് പരിശോധിക്കുക',
    orderSummary: 'ഓർഡർ സംഗ്രഹം',
    subtotal: 'ഉൽപ്പന്ന തുക',
    courierShipping: 'കൊറിയർ ചാർജ്ജ്',
    totalAmount: 'ആകെ തുക',
    deliveryAddress: 'ഡെലിവറി വിലാസം',
    recipientName: 'മുഴുവൻ പേര്',
    mobilePhone: 'മൊബൈൽ നമ്പർ',
    pincode: 'പിൻകോഡ്',
    streetAddress: 'വിലാസം / ഫ്ലാറ്റ് / സ്ഥലം',
    city: 'നഗരം',
    state: 'സംസ്ഥാനം',
    courierMethod: 'കൊറിയർ രീതി',
    standardShipping: 'ഡെൽഹിവെറി എക്സ്പ്രസ്സ്',
    expressShipping: 'ബ്ലൂഡാർട്ട് പ്രയോറിറ്റി എയർ',

    paymentOptions: 'പേയ്‌മെന്റ് രീതികൾ',
    paymentMethod: 'പേയ്‌മെന്റ് തരം',
    payUpiQr: 'UPI & QR കോഡ്',
    payUpiQrSubtitle: 'തൽക്ഷണം 0 ഫീസ്',
    payCod: 'ക്യാഷ് ഓൺ ഡെലിവറി (COD)',
    payCodSubtitle: 'വീട്ടുപടിക്കൽ പണം നൽകാം',
    payCards: 'കാർഡുകൾ / നെറ്റ് ബാങ്കിംഗ്',
    payCardsSubtitle: 'Visa, RuPay, MC',
    scanToPay: 'ഏത് UPI ആപ്പിലും QR സ്കാൻ ചെയ്ത് പണം നൽകുക',
    qrValidFor: 'QR കാലാവധി',
    simulateQrPay: 'QR സ്കാൻ പരിശോധിച്ച് ഉറപ്പാക്കുക',
    verifyingGateway: 'ബാങ്ക് ഗേറ്റ്‌വേയിൽ പരിശോധിക്കുന്നു...',
    upiVerifiedSuccess: 'UPI പേയ്‌മെന്റ് ലഭിച്ചു, വിജയകരം!',
    orEnterUpiId: 'അല്ലെങ്കിൽ UPI ID നൽകുക (ഉദാ: name@oksbi)',
    payViaUpiApp: 'UPI ആപ്പ് വഴി നൽകുക',
    codEligible: 'സൗജന്യ COD ലഭ്യമാണ്',
    codNotice: 'പാഴ്സൽ എത്തുമ്പോൾ പണമായോ UPI QR സ്കാൻ ചെയ്തോ നൽകാം.',
    codOtpTitle: 'സുരക്ഷിത ഡെലിവറി OTP',
    codOtpNotice: 'ഓർഡർ ചെയ്യുമ്പോൾ 4 അക്ക OTP ലഭിക്കും. പാഴ്സൽ പരിശോധിച്ച് ഉറപ്പാക്കിയ ശേഷം മാത്രം ഡെലിവറി ആളിന് നൽകുക.',
    codAgreement: 'പാഴ്സൽ പരിശോധിച്ച ശേഷം കൃത്യം തുക നൽകി OTP പങ്കിടാമെന്ന് സമ്മതിക്കുന്നു.',
    placeCodOrder: 'ക്യാഷ് ഓൺ ഡെലിവറി ഓർഡർ ചെയ്യുക',
    placeUpiOrder: 'UPI QR വഴി ഓർഡർ ചെയ്യുക',
    placeCardOrder: 'കാർഡ് വഴി ഓർഡർ ചെയ്യുക',

    orderPlacedSuccess: 'ഓർഡർ വിജയകരമായി രേഖപ്പെടുത്തി!',
    doorstepOtpCode: 'ഡോർസ്റ്റെപ്പ് ഡെലിവറി OTP',
    courierPartner: 'കൊറിയർ പാർട്ണർ',
    trackingNumber: 'ട്രാക്കിംഗ് നമ്പർ',
    paymentStatus: 'പേയ്‌മെന്റ് സ്റ്റാറ്റസ്',
    paidStatus: 'നൽകി (PAID)',
    codPendingStatus: 'ബാക്കി (ഡെലിവറി സമയം)',
    viewTrackOrders: 'ഓർഡറുകൾ കാണുക & ട്രാക്ക് ചെയ്യുക',
    continueShopping: 'ഷോപ്പിംഗ് തുടരുക',

    myOrdersTitle: 'എന്റെ ഓർഡറുകളും ട്രാക്കിംഗും',
    filterAll: 'എല്ലാ ഓർഡറുകളും',
    filterPlaced: 'ഓർഡർ നൽകി',
    filterConfirmed: 'പാക്കിംഗ് പൂർത്തിയായി',
    filterDispatched: 'വഴിയിൽ',
    filterDelivered: 'ഡെലിവറി ചെയ്തു',
    raiseDispute: 'പരാതി ഉന്നയിക്കുക',
    trackShipment: 'ട്രാക്കിംഗ് കാണുക',
    hideTracking: 'ട്രാക്കിംഗ് മറയ്ക്കുക',
    rateProduct: 'റേറ്റ് ചെയ്യുക',
    supportTicket: 'സഹായ ടിക്കറ്റ്',
    returnReplace: 'തിരികെ നൽകുക / മാറ്റുക',

    themeCustomizerTitle: 'തീം ക്രമീകരണം',
    themeCustomizerDesc: 'നിങ്ങൾക്ക് അനുയോജ്യമായ പ്രകാശമാനമായ നിറങ്ങൾ തെരഞ്ഞെടുക്കൂ.',
    themePreset: 'തീം പ്രീസെറ്റുകൾ',
    themeClassicLight: 'ക്ലാസിക് ലൈറ്റ്',
    themeClassicLightDesc: 'വൃത്തിയുള്ള വെളുപ്പും നീലയും',
    themeBrightElectric: 'ബ്രൈറ്റ് ഇലക്ട്രിക്',
    themeBrightElectricDesc: 'തിളങ്ങുന്ന വെളുപ്പും അൾട്രാ വയലറ്റും',
    themeBrightSunburst: 'ബ്രൈറ്റ് സൺബർസ്റ്റ്',
    themeBrightSunburstDesc: 'സുവർണ്ണ മഞ്ഞയും ഓറഞ്ചും ചേർന്ന പ്രകാശം',
    themeBrightEmerald: 'ബ്രൈറ്റ് എമറാൾഡ്',
    themeBrightEmeraldDesc: 'പുതിയ പുതിനയും പച്ചയും',
    themeMidnightDark: 'മിഡ്‌നൈറ്റ് ഡാർക്ക്',
    themeMidnightDarkDesc: 'കണ്ണുകൾക്ക് ആശ്വാസം നൽകുന്ന കറുത്ത പശ്ചാത്തലം',
    accentColor: 'പ്രധാന നിറം',
    brightnessLevel: 'തെളിച്ചം',
    normalBrightness: 'സാധാരണ തെളിച്ചം',
    highBrightness: 'ഉയർന്ന തിളക്കം (Ultra Bright)',
    resetTheme: 'റീസെറ്റ് ചെയ്യുക',
  },

  te: {
    // Telugu (తెలుగు)
    platformTag: 'వెండర్ హబ్ — మల్టీ-వెండర్ మార్కెట్‌ప్లేస్',
    customerShop: 'కస్టమర్ షాప్',
    vendorPortal: 'వెండర్ పోర్టల్',
    adminPortal: 'అడ్మిన్ పోర్టల్',
    searchPlaceholder: 'ఉత్పత్తులు, బ్రాండ్‌లు, వర్గాలను శోధించండి...',
    cart: 'కార్ట్',
    orders: 'ఆర్డర్లు',
    compare: 'పోల్చండి',
    profile: 'ప్రొఫైల్',
    logout: 'లాగ్ అవుట్',
    login: 'లాగిన్',
    register: 'రిజిస్టర్',
    theme: 'థీమ్',
    language: 'భాష',

    cat_all: 'అన్నీ',
    cat_electronics: 'ఎలక్ట్రానిక్స్',
    cat_fashion: 'ఫ్యాషన్',
    cat_grocery: 'కిరాణా సరుకులు',
    cat_home: 'గృహోపకరణాలు',
    cat_sports: 'క్రీడలు',
    cat_beauty: 'సౌందర్య సాధనాలు',

    marketplaceCatalog: 'మార్కెట్‌ప్లేస్ కేటలాగ్',
    verifiedLocalProducts: 'ధృవీకరించబడిన స్థానిక విక్రేతల ఉత్పత్తులు సిద్ధంగా ఉన్నాయి',
    allCategories: 'అన్ని వర్గాలు',
    filterBy: 'ఫిల్టర్లు',
    sortBy: 'క్రమబద్ధీకరించు',
    sort_newest: 'కొత్తగా వచ్చినవి',
    sort_price_asc: 'ధర: తక్కువ నుండి ఎక్కువ',
    sort_price_desc: 'ధర: ఎక్కువ నుండి తక్కువ',
    sort_rating: 'ఉత్తమ రేటింగ్',
    inStockOnly: 'స్టాక్ ఉన్నవి మాత్రమే',
    fastDeliveryOnly: 'వేగవంతమైన డెలివరీ (24 గం)',
    resetFilters: 'ఫిల్టర్లు రీసెట్ చేయండి',
    addToCart: 'కార్ట్‌కు జోడించు',
    addedToCart: 'కార్ట్‌కు చేర్చబడింది',
    viewProduct: 'వివరాలు చూడండి',
    freeShipping: 'ఉచిత డెలివరీ',
    codAvailable: 'క్యాష్ ఆన్ డెలివరీ అందుబాటులో ఉంది',
    inStock: 'స్టాక్ ఉంది',
    lowStock: 'తక్కువ స్టాక్',
    outOfStock: 'స్టాక్ లేదు',
    unitsLeft: 'మిగిలి ఉన్నవి',

    shoppingCart: 'షాపింగ్ కార్ట్',
    cartItemsCount: 'కార్ట్‌లోని వస్తువులు',
    cartEmpty: 'మీ కార్ట్ ఖాళీగా ఉంది',
    cartEmptyDesc: 'ఉత్పత్తులను జోడించడానికి మా కేటలాగ్‌ను చూడండి.',
    exploreCatalog: 'ఉత్పత్తులను అన్వేషించండి',
    orderSummary: 'ఆర్డర్ సారాంశం',
    subtotal: 'వస్తువుల మొత్తం',
    courierShipping: 'కొరియర్ ఛార్జీలు',
    totalAmount: 'మొత్తం చెల్లించవలసినది',
    deliveryAddress: 'డెలివరీ చిరునామా',
    recipientName: 'పూర్తి పేరు',
    mobilePhone: 'మొబైల్ సంఖ్య',
    pincode: 'పిన్‌కోడ్',
    streetAddress: 'వీధి / ఫ్లాట్ చిరునామా',
    city: 'నగరం',
    state: 'రాష్ట్రం',
    courierMethod: 'కొరియర్ విధానం',
    standardShipping: 'ఢిల్లీవరీ ఎక్స్‌ప్రెస్',
    expressShipping: 'బ్లూడార్ట్ ప్రయారిటీ ఎయిర్',

    paymentOptions: 'చెల్లింపు ఎంపికలు',
    paymentMethod: 'చెల్లింపు పద్ధతి',
    payUpiQr: 'UPI & QR కోడ్',
    payUpiQrSubtitle: 'తక్షణమే 0 ఫీజు',
    payCod: 'క్యాష్ ఆన్ డెలివరీ (COD)',
    payCodSubtitle: 'ఇంటి వద్ద చెల్లించండి',
    payCards: 'కార్డులు / బ్యాంకింగ్',
    payCardsSubtitle: 'Visa, RuPay, MC',
    scanToPay: 'ఏదైనా UPI యాప్‌తో QR స్కాన్ చేసి చెల్లించండి',
    qrValidFor: 'QR గడువు సమయం',
    simulateQrPay: 'QR స్కాన్ ధృవీకరించి పూర్తి చేయండి',
    verifyingGateway: 'బ్యాంక్ గేట్‌వేలో ధృవీకరిస్తోంది...',
    upiVerifiedSuccess: 'UPI చెల్లింపు పూర్తయింది, ధృవీకరించబడింది!',
    orEnterUpiId: 'లేదా UPI ID నమోదు చేయండి (ఉదా: name@oksbi)',
    payViaUpiApp: 'UPI యాప్ ద్వారా చెల్లించండి',
    codEligible: 'ఉచిత COD కి అర్హమైనది',
    codNotice: 'పార్శిల్ డెలివరీ సమయంలో నగదు లేదా UPI QR ద్వారా చెల్లించండి.',
    codOtpTitle: 'సురక్షిత డెలివరీ OTP',
    codOtpNotice: 'ఆర్డర్ చేసిన వెంటనే 4 అంకెల OTP వస్తుంది. పార్శిల్ సరిచూసుకున్న తర్వాత మాత్రమే డెలివరీ ఏజెంట్‌తో పంచుకోండి.',
    codAgreement: 'పార్శిల్ పరిశీలించి ఖచ్చితమైన మొత్తం చెల్లించి OTP పంచుకోవడానికి అంగీకరిస్తున్నాను.',
    placeCodOrder: 'క్యాష్ ఆన్ డెలివరీ ఆర్డర్ చేయండి',
    placeUpiOrder: 'UPI QR ద్వారా ఆర్డర్ చేయండి',
    placeCardOrder: 'కార్డ్ ద్వారా ఆర్డర్ చేయండి',

    orderPlacedSuccess: 'ఆర్డర్ విజయవంతంగా నమోదైంది!',
    doorstepOtpCode: 'డోర్‌స్టెప్ డెలివరీ OTP',
    courierPartner: 'కొరియర్ భాగస్వామి',
    trackingNumber: 'ట్రాకింగ్ సంఖ్య',
    paymentStatus: 'చెల్లింపు స్థితి',
    paidStatus: 'చెల్లించబడింది (PAID)',
    codPendingStatus: 'పెండింగ్ (డెలివరీ సమయంలో)',
    viewTrackOrders: 'నా ఆర్డర్‌లను ట్రాక్ చేయండి',
    continueShopping: 'షాపింగ్ కొనసాగించండి',

    myOrdersTitle: 'నా ఆర్డర్లు & ప్రత్యక్ష ట్రాకింగ్',
    filterAll: 'అన్ని ఆర్డర్లు',
    filterPlaced: 'ఆర్డర్ స్వీకరించబడింది',
    filterConfirmed: 'ప్యాకింగ్ పూర్తయింది',
    filterDispatched: 'మార్గంలో ఉంది',
    filterDelivered: 'డెలివరీ చేయబడింది',
    raiseDispute: 'సమస్యను నివేదించండి',
    trackShipment: 'షిప్‌మెంట్ ట్రాక్ చేయండి',
    hideTracking: 'ట్రాకింగ్ దాచండి',
    rateProduct: 'రేటింగ్ ఇవ్వండి',
    supportTicket: 'సహాయ టిక్కెట్',
    returnReplace: 'రిటర్న్ / రీప్లేస్‌మెంట్',

    themeCustomizerTitle: 'థీమ్ అనుకూలీకరణ',
    themeCustomizerDesc: 'మీకు నచ్చిన ప్రకాశవంతమైన రంగులతో ప్లాట్‌ఫారమ్‌ను తీర్చిదిద్దుకోండి.',
    themePreset: 'రంగుల థీమ్‌లు',
    themeClassicLight: 'క్లాసిక్ లైట్',
    themeClassicLightDesc: 'స్వచ్ఛమైన తెలుపు మరియు నీలం రంగు',
    themeBrightElectric: 'బ్రైట్ ఎలక్ట్రిక్',
    themeBrightElectricDesc: 'అధిక కాంతిమంతమైన తెలుపు మరియు నీలి మెరుపులు',
    themeBrightSunburst: 'బ్రైట్ సన్‌బర్స్ట్',
    themeBrightSunburstDesc: 'సూర్యకాంతి బంగారు పసుపు మరియు నారింజ',
    themeBrightEmerald: 'బ్రైట్ ఎమరాల్డ్',
    themeBrightEmeraldDesc: 'సహజమైన తాజా ఆకుపచ్చ రంగు',
    themeMidnightDark: 'మిడ్‌నైట్ డార్క్',
    themeMidnightDarkDesc: 'కళ్ళకు హాయిగా ఉండే నల్లని రంగు',
    accentColor: 'ప్రధాన రంగు',
    brightnessLevel: 'కాంతి తీవ్రత',
    normalBrightness: 'సాధారణ కాంతి',
    highBrightness: 'అధిక కాంతి (Ultra Glow)',
    resetTheme: 'రీసెట్ చేయండి',
  },

  kn: {
    // Kannada (ಕನ್ನಡ)
    platformTag: 'ವೆಂಡರ್ ಹಬ್ — ಮಲ್ಟಿ-ವೆಂಡರ್ ಮಾರುಕಟ್ಟೆ',
    customerShop: 'ಗ್ರಾಹಕರ ಶಾಪ್',
    vendorPortal: 'ಮಾರಾಟಗಾರರ ಪೋರ್ಟಲ್',
    adminPortal: 'ನಿರ್ವಾಹಕರ ಪೋರ್ಟಲ್',
    searchPlaceholder: 'ಉತ್ಪನ್ನಗಳು, ಬ್ರ್ಯಾಂಡ್‌ಗಳು, ವರ್ಗಗಳನ್ನು ಹುಡುಕಿ...',
    cart: 'ಕಾರ್ಟ್',
    orders: 'ಆರ್ಡರ್‌ಗಳು',
    compare: 'ಹೋಲಿಕೆ',
    profile: 'ಪ್ರೊಫೈಲ್',
    logout: 'ನಿರ್ಗಮಿಸಿ',
    login: 'ಲಾಗಿನ್',
    register: 'ನೋಂದಣಿ',
    theme: 'ಥೀಮ್',
    language: 'ಭಾಷೆ',

    cat_all: 'ಎಲ್ಲವೂ',
    cat_electronics: 'ಎಲೆಕ್ಟ್ರಾನಿಕ್ಸ್',
    cat_fashion: 'ಫ್ಯಾಷನ್',
    cat_grocery: 'ದಿನಸಿ ವಸ್ತುಗಳು',
    cat_home: 'ಮನೆ ಮತ್ತು ಜೀವನಶೈಲಿ',
    cat_sports: 'ಕ್ರೀಡೆ',
    cat_beauty: 'ಸೌಂದರ್ಯ ಸಾಧನಗಳು',

    marketplaceCatalog: 'ಮಾರುಕಟ್ಟೆ ಕ್ಯಾಟಲಾಗ್',
    verifiedLocalProducts: 'ಪರಿಶೀಲಿಸಿದ ಸ್ಥಳೀಯ ಮಾರಾಟಗಾರರ ಉತ್ಪನ್ನಗಳು ಸ್ಟಾಕ್‌ನಲ್ಲಿವೆ',
    allCategories: 'ಎಲ್ಲಾ ವರ್ಗಗಳು',
    filterBy: 'ಫಿಲ್ಟರ್‌ಗಳು',
    sortBy: 'ವಿಂಗಡಿಸಿ',
    sort_newest: 'ಹೊಸದಾಗಿ ಬಂದಿರುವುದು',
    sort_price_asc: 'ಬೆಲೆ: ಕಡಿಮೆಯಿಂದ ಹೆಚ್ಚಿಗೆ',
    sort_price_desc: 'ಬೆಲೆ: ಹೆಚ್ಚಿನಿಂದ ಕಡಿಮೆಗೆ',
    sort_rating: 'ಉತ್ತಮ ರೇಟಿಂಗ್',
    inStockOnly: 'ಸ್ಟಾಕ್ ಇರುವವು ಮಾತ್ರ',
    fastDeliveryOnly: 'ವೇಗದ ಡೆಲಿವರಿ (24 ಗಂಟೆ)',
    resetFilters: 'ಫಿಲ್ಟರ್‌ಗಳನ್ನು ಮರುಹೊಂದಿಸಿ',
    addToCart: 'ಕಾರ್ಟ್‌ಗೆ ಸೇರಿಸಿ',
    addedToCart: 'ಕಾರ್ಟ್‌ಗೆ ಸೇರಿಸಲಾಗಿದೆ',
    viewProduct: 'ವಿವರಗಳನ್ನು ನೋಡಿ',
    freeShipping: 'ಉಚಿತ ಸಾಗಣೆ',
    codAvailable: 'ಕ್ಯಾಶ್ ಆನ್ ಡೆಲಿವರಿ ಲಭ್ಯವಿದೆ',
    inStock: 'ಸ್ಟಾಕ್‌ನಲ್ಲಿದೆ',
    lowStock: 'ಕಡಿಮೆ ಸ್ಟಾಕ್',
    outOfStock: 'ಸ್ಟಾಕ್ ಮುಗಿದಿದೆ',
    unitsLeft: 'ಉಳಿದಿರುವ ಯೂನಿಟ್‌ಗಳು',

    shoppingCart: 'ಶಾಪಿಂಗ್ ಕಾರ್ಟ್',
    cartItemsCount: 'ಕಾರ್ಟ್‌ನಲ್ಲಿರುವ ವಸ್ತುಗಳು',
    cartEmpty: 'ನಿಮ್ಮ ಕಾರ್ಟ್ ಖಾಲಿಯಾಗಿದೆ',
    cartEmptyDesc: 'ಉತ್ಪನ್ನಗಳನ್ನು ಸೇರಿಸಲು ನಮ್ಮ ಕ್ಯಾಟಲಾಗ್ ಪರಿಶೀಲಿಸಿ.',
    exploreCatalog: 'ಕ್ಯಾಟಲಾಗ್ ಅನ್ವೇಷಿಸಿ',
    orderSummary: 'ಆರ್ಡರ್ ಸಾರಾಂಶ',
    subtotal: 'ವಸ್ತುಗಳ ಉಪಮೊತ್ತ',
    courierShipping: 'ಕೊರಿಯರ್ ಶುಲ್ಕ',
    totalAmount: 'ಒಟ್ಟು ಮೊತ್ತ',
    deliveryAddress: 'ಡೆಲಿವರಿ ವಿಳಾಸ',
    recipientName: 'ಪೂರ್ಣ ಹೆಸರು',
    mobilePhone: 'ಮೊಬೈಲ್ ಸಂಖ್ಯೆ',
    pincode: 'ಪಿನ್‌ಕೋಡ್',
    streetAddress: 'ರಸ್ತೆ ವಿಳಾಸ / ಫ್ಲಾಟ್',
    city: 'ನಗರ',
    state: 'ರಾಜ್ಯ',
    courierMethod: 'ಕೊರಿಯರ್ ವಿಧಾನ',
    standardShipping: 'ಡೆಲ್ಹಿವರಿ ಎಕ್ಸ್‌ಪ್ರೆಸ್',
    expressShipping: 'ಬ್ಲೂಡಾರ್ಟ್ ಪ್ರಿಯಾರಿಟಿ ಏರ್',

    paymentOptions: 'ಪಾವತಿ ಆಯ್ಕೆಗಳು',
    paymentMethod: 'ಪಾವತಿ ವಿಧಾನ',
    payUpiQr: 'UPI & QR ಕೋಡ್',
    payUpiQrSubtitle: 'ತಕ್ಷಣವೇ 0 ಶುಲ್ಕ',
    payCod: 'ಕ್ಯಾಶ್ ಆನ್ ಡೆಲಿವರಿ (COD)',
    payCodSubtitle: 'ಮನೆ ಬಾಗಿಲಲ್ಲಿ ಪಾವತಿಸಿ',
    payCards: 'ಕಾರ್ಡ್‌ಗಳು / ಬ್ಯಾಂಕಿಂಗ್',
    payCardsSubtitle: 'Visa, RuPay, MC',
    scanToPay: 'ಯಾವುದೇ UPI ಆಪ್ ಮೂಲಕ QR ಸ್ಕ್ಯಾನ್ ಮಾಡಿ ಪಾವತಿಸಿ',
    qrValidFor: 'QR ಮಾನ್ಯತೆಯ ಸಮಯ',
    simulateQrPay: 'QR ಸ್ಕ್ಯಾನ್ ಪರಿಶೀಲಿಸಿ ದೃಢೀಕರಿಸಿ',
    verifyingGateway: 'ಬ್ಯಾಂಕ್ ಗೇಟ್‌ವೇನಲ್ಲಿ ಪರಿಶೀಲಿಸಲಾಗುತ್ತಿದೆ...',
    upiVerifiedSuccess: 'UPI ಪಾವತಿ ಯಶಸ್ವಿಯಾಗಿ ಸ್ವೀಕರಿಸಲಾಗಿದೆ!',
    orEnterUpiId: 'ಅಥವಾ UPI ID ನಮೂದಿಸಿ (ಉದಾ: name@oksbi)',
    payViaUpiApp: 'UPI ಆಪ್ ಮೂಲಕ ಪಾವತಿಸಿ',
    codEligible: 'ಉಚಿತ COD ಗೆ ಅರ್ಹವಾಗಿದೆ',
    codNotice: 'ಪಾರ್ಸಲ್ ಬಂದಾಗ ನಗದು ಅಥವಾ UPI QR ಸ್ಕ್ಯಾನ್ ಮಾಡಿ ಪಾವತಿಸಿ.',
    codOtpTitle: 'ಸುರಕ್ಷಿತ ಡೆಲಿವರಿ OTP',
    codOtpNotice: 'ಆರ್ಡರ್ ಮಾಡಿದ ತಕ್ಷಣ 4 ಅಂಕಿಯ ಭದ್ರತಾ OTP ಲಭ್ಯವಾಗುತ್ತದೆ. ಪಾರ್ಸಲ್ ಪರೀಕ್ಷಿಸಿದ ನಂತರವೇ ಡೆಲಿವರಿ ಏಜೆಂಟ್‌ಗೆ ನೀಡಿ.',
    codAgreement: 'ಪಾರ್ಸಲ್ ಪರೀಕ್ಷಿಸಿ ನಿಖರ ಮೊತ್ತ ಪಾವತಿಸಿ OTP ಹಂಚಿಕೊಳ್ಳಲು ಸಮ್ಮತಿಸುತ್ತೇನೆ.',
    placeCodOrder: 'COD ಆರ್ಡರ್ ದೃಢೀಕರಿಸಿ',
    placeUpiOrder: 'UPI QR ಮೂಲಕ ಆರ್ಡರ್ ಮಾಡಿ',
    placeCardOrder: 'ಕಾರ್ಡ್ ಮೂಲಕ ಆರ್ಡರ್ ಮಾಡಿ',

    orderPlacedSuccess: 'ಆರ್ಡರ್ ಯಶಸ್ವಿಯಾಗಿ ಸಲ್ಲಿಸಲಾಗಿದೆ!',
    doorstepOtpCode: 'ಡೋರ್‌ಸ್ಟೆಪ್ ಡೆಲಿವರಿ OTP',
    courierPartner: 'ಕೊರಿಯರ್ ಪಾಲುದಾರ',
    trackingNumber: 'ಟ್ರಾಕಿಂಗ್ ಸಂಖ್ಯೆ',
    paymentStatus: 'ಪಾವತಿ ಸ್ಥಿತಿ',
    paidStatus: 'ಪಾವತಿಸಲಾಗಿದೆ (PAID)',
    codPendingStatus: 'ಬಾಕಿ (ಡೆಲಿವರಿ ಸಮಯದಲ್ಲಿ)',
    viewTrackOrders: 'ನನ್ನ ಆರ್ಡರ್‌ಗಳನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ',
    continueShopping: 'ಶಾಪಿಂಗ್ ಮುಂದುವರಿಸಿ',

    myOrdersTitle: 'ನನ್ನ ಆರ್ಡರ್‌ಗಳು ಮತ್ತು ಟ್ರ್ಯಾಕಿಂಗ್',
    filterAll: 'ಎಲ್ಲಾ ಆರ್ಡರ್‌ಗಳು',
    filterPlaced: 'ಆರ್ಡರ್ ಸ್ವೀಕರಿಸಲಾಗಿದೆ',
    filterConfirmed: 'ಪ್ಯಾಕಿಂಗ್ ಆಗಿದೆ',
    filterDispatched: 'ದಾರಿಯಲ್ಲಿದೆ',
    filterDelivered: 'ತಲುಪಿಸಲಾಗಿದೆ',
    raiseDispute: 'ದೂರು ಸಲ್ಲಿಸಿ',
    trackShipment: 'ನೇರ ಟ್ರ್ಯಾಕಿಂಗ್',
    hideTracking: 'ಟ್ರ್ಯಾಕಿಂಗ್ ಮರೆಮಾಡಿ',
    rateProduct: 'ರೇಟಿಂಗ್ ನೀಡಿ',
    supportTicket: 'ಸಹಾಯ ಟಿಕೆಟ್',
    returnReplace: 'ಹಿಂತಿರುಗಿಸಿ / ಬದಲಾಯಿಸಿ',

    themeCustomizerTitle: 'ಥೀಮ್ ಗ್ರಾಹಕೀಕರಣ',
    themeCustomizerDesc: 'ನಿಮ್ಮ ಮೆಚ್ಚಿನ ಪ್ರಕಾಶಮಾನವಾದ ಬಣ್ಣಗಳಿಂದ ವೇದಿಕೆಯನ್ನು ಕಸ್ಟಮೈಸ್ ಮಾಡಿ.',
    themePreset: 'ಥೀಮ್ ಆಯ್ಕೆಗಳು',
    themeClassicLight: 'ಕ್ಲಾಸಿಕ್ ಲೈಟ್',
    themeClassicLightDesc: 'ಸ್ವಚ್ಛವಾದ ಬಿಳಿ ಮತ್ತು ನೀಲಿ ಬಣ್ಣ',
    themeBrightElectric: 'ಬ್ರೈಟ್ ಎಲೆಕ್ಟ್ರಿಕ್',
    themeBrightElectricDesc: 'ಅತ್ಯುನ್ನತ ಪ್ರಕಾಶಮಾನ ಬಿಳಿ ಮತ್ತು ನೇರಳೆ ಹೊಳಪು',
    themeBrightSunburst: 'ಬ್ರೈಟ್ ಸನ್‌ಬರ್ಸ್ಟ್',
    themeBrightSunburstDesc: 'ಸೂರ್ಯನ ಬಂಗಾರದ ಹಳದಿ ಮತ್ತು ಕೇಸರಿ',
    themeBrightEmerald: 'ಬ್ರೈಟ್ ಎಮರಾಲ್ಡ್',
    themeBrightEmeraldDesc: 'ನೈಸರ್ಗಿಕ ತಾಜಾ ಹಸಿರು ಬಣ್ಣ',
    themeMidnightDark: 'ಮಿಡ್‌ನೈಟ್ ಡಾರ್ಕ್',
    themeMidnightDarkDesc: 'ಕಣ್ಣಿಗೆ ಆರಾಮದಾಯಕವಾದ ಗಾಢ ಕಪ್ಪು ಹಿನ್ನೆಲೆ',
    accentColor: 'ಮುಖ್ಯ ಬಣ್ಣ',
    brightnessLevel: 'ಪ್ರಕಾಶತೆಯ ಮಟ್ಟ',
    normalBrightness: 'ಸಾಮಾನ್ಯ ಪ್ರಕಾಶ',
    highBrightness: 'ಗರಿಷ್ಠ ಪ್ರಕಾಶ (Ultra Glow)',
    resetTheme: 'ಮರುಹೊಂದಿಸಿ',
  },

  hi: {
    // Hindi (हिन्दी)
    platformTag: 'वेंडर हब — मल्टी-वेंडर मार्केटप्लेस',
    customerShop: 'ग्राहक शॉप',
    vendorPortal: 'विक्रेता पोर्टल',
    adminPortal: 'एडमिन पोर्टल',
    searchPlaceholder: 'उत्पाद, ब्रांड, श्रेणियां खोजें...',
    cart: 'कार्ट',
    orders: 'ऑर्डर',
    compare: 'तुलना',
    profile: 'प्रोफाइल',
    logout: 'लॉग आउट',
    login: 'लॉग इन',
    register: 'पंजीकरण',
    theme: 'थीम',
    language: 'भाषा',

    cat_all: 'सभी',
    cat_electronics: 'इलेक्ट्रॉनिक्स',
    cat_fashion: 'फैशन',
    cat_grocery: 'किराना',
    cat_home: 'घर और रहन-सहन',
    cat_sports: 'खेल कूद',
    cat_beauty: 'सौंदर्य प्रसाधन',

    marketplaceCatalog: 'मार्केटप्लेस कैटलॉग',
    verifiedLocalProducts: 'सत्यापित स्थानीय विक्रेताओं के उत्पाद स्टॉक में उपलब्ध',
    allCategories: 'सभी श्रेणियां',
    filterBy: 'फ़िल्टर',
    sortBy: 'क्रमबद्ध करें',
    sort_newest: 'नवीनतम उत्पाद',
    sort_price_asc: 'मूल्य: कम से अधिक',
    sort_price_desc: 'मूल्य: अधिक से कम',
    sort_rating: 'शीर्ष ग्राहक रेटिंग',
    inStockOnly: 'केवल स्टॉक में उपलब्ध',
    fastDeliveryOnly: 'तेज़ डिलीवरी (24 घंटे)',
    resetFilters: 'फ़िल्टर हटाएं',
    addToCart: 'कार्ट में जोड़ें',
    addedToCart: 'कार्ट में जोड़ा गया',
    viewProduct: 'विवरण देखें',
    freeShipping: 'निःशुल्क डिलीवरी',
    codAvailable: 'कैश ऑन डिलीवरी उपलब्ध',
    inStock: 'स्टॉक में उपलब्ध',
    lowStock: 'सीमित स्टॉक',
    outOfStock: 'स्टॉक समाप्त',
    unitsLeft: 'पीस बाकी',

    shoppingCart: 'शॉपिंग कार्ट',
    cartItemsCount: 'कार्ट में कुल वस्तुएं',
    cartEmpty: 'आपकी कार्ट वर्तमान में खाली है',
    cartEmptyDesc: 'इलेक्ट्रॉनिक्स, फैशन और घरेलू सामान जोड़ने के लिए कैटलॉग देखें।',
    exploreCatalog: 'उत्पाद कैटलॉग देखें',
    orderSummary: 'ऑर्डर सारांश',
    subtotal: 'सामग्री उप-योग',
    courierShipping: 'कूरियर शिपिंग',
    totalAmount: 'कुल राशि',
    deliveryAddress: 'डिलीवरी का पता',
    recipientName: 'प्राप्तकर्ता का पूरा नाम',
    mobilePhone: 'मोबाइल नंबर',
    pincode: 'डाक पिनकोड',
    streetAddress: 'सड़क का पता / फ्लैट / मंजिल',
    city: 'शहर',
    state: 'राज्य',
    courierMethod: 'कूरियर डिलीवरी माध्यम',
    standardShipping: 'डेल्हीवरी एक्सप्रेस (3-5 दिन)',
    expressShipping: 'ब्लूडार्ट प्रायोरिटी एयर (1-2 दिन)',

    paymentOptions: 'भुगतान विकल्प',
    paymentMethod: 'भुगतान विधि',
    payUpiQr: 'UPI और QR कोड',
    payUpiQrSubtitle: 'तत्काल 0 शुल्क',
    payCod: 'कैश ऑन डिलीवरी (COD)',
    payCodSubtitle: 'दरवाजे पर नकद भुगतान',
    payCards: 'कार्ड / नेट बैंकिंग',
    payCardsSubtitle: 'Visa, RuPay, MC',
    scanToPay: 'किसी भी UPI ऐप से QR स्कैन करके भुगतान करें',
    qrValidFor: 'QR की वैधता समय',
    simulateQrPay: 'QR स्कैन सत्यापित करें और भुगतान पूरा करें',
    verifyingGateway: 'बैंक गेटवे से सत्यापन जारी है...',
    upiVerifiedSuccess: 'UPI भुगतान सफलतापूर्वक सत्यापित हुआ!',
    orEnterUpiId: 'या अपनी UPI ID दर्ज करें (उदा: name@oksbi)',
    payViaUpiApp: 'UPI ऐप से भुगतान करें',
    codEligible: 'निःशुल्क COD उपलब्ध',
    codNotice: 'पार्सल मिलने पर नकद या कूरियर एजेंट के UPI QR से भुगतान करें।',
    codOtpTitle: 'सुरक्षित डिलीवरी OTP',
    codOtpNotice: 'ऑर्डर करने पर 4 अंकों का सुरक्षा OTP मिलेगा। पार्सल की जांच करने के बाद ही कूरियर एजेंट को OTP दें।',
    codAgreement: 'मैं पार्सल की जांच के बाद सटीक राशि तैयार रखने और OTP साझा करने पर सहमत हूं।',
    placeCodOrder: 'कैश ऑन डिलीवरी ऑर्डर की पुष्टि करें',
    placeUpiOrder: 'UPI QR से ऑर्डर करें',
    placeCardOrder: 'कार्ड से ऑर्डर करें',

    orderPlacedSuccess: 'ऑर्डर सफलतापूर्वक दर्ज किया गया!',
    doorstepOtpCode: 'डोरस्टेप डिलीवरी OTP',
    courierPartner: 'कूरियर पार्टनर',
    trackingNumber: 'ट्रैकिंग नंबर',
    paymentStatus: 'भुगतान स्थिति',
    paidStatus: 'भुगतान संपन्न (PAID)',
    codPendingStatus: 'लंबित (डिलीवरी के समय देय)',
    viewTrackOrders: 'मेरे ऑर्डर देखें और ट्रैक करें',
    continueShopping: 'खरीदारी जारी रखें',

    myOrdersTitle: 'मेरे ऑर्डर और लाइव ट्रैकिंग',
    filterAll: 'सभी ऑर्डर',
    filterPlaced: 'ऑर्डर प्राप्त हुआ',
    filterConfirmed: 'पैकिंग सत्यापित',
    filterDispatched: 'रास्ते में है',
    filterDelivered: 'डिलीवर हो गया',
    raiseDispute: 'विवाद दर्ज करें',
    trackShipment: 'लाइव ट्रैकिंग देखें',
    hideTracking: 'ट्रैकिंग छिपाएं',
    rateProduct: 'रेटिंग दें',
    supportTicket: 'सहायता टिकट',
    returnReplace: 'वापसी / बदलाव',

    themeCustomizerTitle: 'थीम कस्टमाइज़र',
    themeCustomizerDesc: 'अपनी पसंद के अनुसार चमकीले, सौम्य या जीवंत रंगों में थीम चुनें।',
    themePreset: 'थीम प्रीसेट',
    themeClassicLight: 'क्लासिक लाइट',
    themeClassicLightDesc: 'स्वच्छ सफेद और इंडिगो रंग',
    themeBrightElectric: 'ब्राइट इलेक्ट्रिक',
    themeBrightElectricDesc: 'चमकदार सफेद और इलेक्ट्रिक वॉयलेट/स्यान रंग',
    themeBrightSunburst: 'ब्राइट सनबर्स्ट',
    themeBrightSunburstDesc: 'धूप जैसी सुनहरी पीली और नारंगी सतह',
    themeBrightEmerald: 'ब्राइट एमराल्ड',
    themeBrightEmeraldDesc: 'ताज़ा पुदीना और पन्ना हरा रंग',
    themeMidnightDark: 'मिडनाइट डार्क',
    themeMidnightDarkDesc: 'आंखों के लिए आरामदायक गहरा डार्क मोड',
    accentColor: 'मुख्य रंग (Accent Color)',
    brightnessLevel: 'चमक स्तर (Brightness)',
    normalBrightness: 'सामान्य चमक',
    highBrightness: 'अल्ट्रा ब्राइट ग्लो (High Glow)',
    resetTheme: 'डिफ़ॉल्ट पर रीसेट करें',
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(() => {
    try {
      return localStorage.getItem('vm_language') || 'en';
    } catch {
      return 'en';
    }
  });

  const setLanguage = useCallback((langCode) => {
    if (TRANSLATIONS[langCode]) {
      setLanguageState(langCode);
      try {
        localStorage.setItem('vm_language', langCode);
      } catch (err) {
        console.error(err);
      }
    }
  }, []);

  const t = useCallback((key, fallback = '') => {
    const langDict = TRANSLATIONS[language] || TRANSLATIONS.en;
    if (langDict && langDict[key] !== undefined) {
      return langDict[key];
    }
    // Fallback to English
    if (TRANSLATIONS.en && TRANSLATIONS.en[key] !== undefined) {
      return TRANSLATIONS.en[key];
    }
    return fallback || key;
  }, [language]);

  const currentLangMeta = useMemo(() => {
    return LANGUAGES.find((l) => l.code === language) || LANGUAGES[0];
  }, [language]);

  const value = useMemo(() => ({
    language,
    setLanguage,
    t,
    languages: LANGUAGES,
    currentLangMeta,
  }), [language, setLanguage, t, currentLangMeta]);

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return ctx;
};
